---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: NetApp Keystoneサブスクリプションでクラウドサービスを購入した場合は、BlueXPからそれらのサービスにアクセスして管理できます。 
---
= KeystoneとBlueXPの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXPは、オンプレミス環境とクラウド環境にわたってデータを構築、保護、ガバナンスするための単一のコントロールプレーンです。NetApp Keystone サブスクリプションでクラウドサービスを購入した場合は、BlueXPからそれらのサービスにアクセスして管理できます。

BlueXP Digital Advisorのダッシュボードでは、グラフィカルビューとドリルダウン機能を使用してKeystoneサブスクリプションの使用状況を監視し、レポートを生成できます。Digital AdvisorダッシュボードとKeystoneの詳細については、を参照してください link:../integrations/aiq-keystone-details.html["Keystoneサブスクリプションのダッシュボードとレポート"]。

Keystoneをご利用のお客様は、Cloud Volumes ONTAP サブスクリプションをお持ちの場合、Keystoneサービスを使用してCloud Volumes ONTAP の使用量を課金し、BlueXPを使用して請求および消費の詳細を確認できます。

そのためには、1つ以上のBlueXPアカウントを作成し、それらをKeystoneアカウントにリンクする必要があります。Keystoneを通じてクラウドサービスを購入する場合は、BlueXPアカウントの詳細をKeystone Success Manager（KSM）に提供する必要があります。これにより、Keystoneサブスクリプションを使用してクラウドサービスの利用率を適切に計測し、課金することができます。

KeystoneとBlueXPの詳細については、BlueXPドキュメントの次のリンクを参照してください。

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Keystoneサブスクリプション"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Keystoneサブスクリプションの管理"^]

