---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Keystoneのドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: Keystone STaaSの新機能
      url: "/release-notes/whats-new.html"
    - title: 解決済みの問題です
      url: "/release-notes/fixed-issues.html"
    - title: 既知の問題
      url: "/release-notes/known-issues.html"
    - title: 既知の制限
      url: "/release-notes/known-limitations.html"
  - title: Keystoneの詳細をご確認ください
    entries:
    - title: 概要
      url: "/concepts/overview.html"
    - title: Keystoneインフラ
      url: "/concepts/infra.html"
    - title: Keystoneコレクタ
      url: "/installation/installation-overview.html"
    - title: コンポーネント
      url: "/concepts/components.html"
    - title: データフロー
      url: "/concepts/data-flow.html"
    - title: 運用モデル
      url: "/concepts/operational-models.html"
  - title: Keystoneをセットアップおよび設定する
    entries:
    - title: 要件
      entries:
      - title: 仮想インフラ
        url: "/installation/vapp-prereqs.html"
      - title: Linux の場合
        url: "/installation/linux-prereqs.html"
      - title: ONTAPとStorageGRID
        url: "/installation/addl-req.html"
    - title: Keystone Collectorをインストールします
      entries:
      - title: VMware vSphereに導入
        url: "/installation/vapp-installation.html"
      - title: Linuxへのインストール
        url: "/installation/linux-installation.html"
      - title: Keystoneソフトウェアの自動検証
        url: "/installation/validation.html"
    - title: Keystoneコレクタを設定する
      url: "/installation/configuration.html"
    - title: AutoSupport を設定します
      url: "/installation/asup-config.html"
    - title: Keystone Collectorのセキュリティ
      url: "/installation/security.html"
    - title: 課金のために収集されたデータ
      url: "/installation/data-collection.html"
  - title: 監視とアップグレード
    entries:
    - title: Keystone Collectorの健全性を監視する
      url: "/installation/monitor-health.html"
    - title: Keystone Collectorをアップグレードします
      url: "/installation/upgrade.html"
  - title: Keystoneダッシュボード
    entries:
    - title: Keystoneダッシュボードの概要
      url: "/integrations/keystone-aiq.html"
    - title: 使用状況の詳細を表示してレポートを生成
      url: "/integrations/aiq-keystone-details.html"
    - title: "[サブスクリプション]タブ"
      url: "/integrations/subscriptions-tab.html"
    - title: "[Current Consumption]タブ"
      url: "/integrations/current-usage-tab.html"
    - title: "[Consumption Trend]タブ"
      url: "/integrations/capacity-trend-tab.html"
    - title: "[Volumes & Objects]タブ"
      url: "/integrations/volumes-objects-tab.html"
    - title: "[Assets]タブ"
      url: "/integrations/assets-tab.html"
    - title: "[パフォーマンス]タブ"
      url: "/integrations/performance-tab.html"
    - title: KeystoneとBlueXPの詳細
      url: "/integrations/keystone-cm.html"
  - title: Keystone STaaSサービス
    entries:
    - title: 指標と定義
      url: "/concepts/metrics.html"
    - title: ストレージQoS
      url: "/concepts/qos.html"
    - title: サポートされるストレージ
      url: "/concepts/supported-storage-services.html"
    - title: サポートされる容量
      url: "/concepts/supported-storage-capacity.html"
    - title: サービスレベル
      url: "/concepts/service-levels.html"
    - title: サービスレベルの容量要件
      url: "/concepts/capacity-requirements.html"
    - title: Keystoneサブスクリプションサービスバージョン1
      url: "/subscription-services-v1.html"
    - title: アドオンサービス
      entries:
      - title: 高度なデータ保護
        url: "/concepts/adp.html"
      - title: データインフラの分析情報
        url: "/concepts/data-infra-insights.html"
      - title: データの階層化
        url: "/concepts/data-tiering.html"
      - title: Equinixを基盤とするサービス
        url: "/concepts/equinix.html"
      - title: 返品不可、不揮発性コンポーネント、SnapLock準拠
        url: "/concepts/nrnvc.html"
      - title: 米国市民サポート（USCS）
        url: "/concepts/uscs.html"
  - title: Keystone STaaSのSLA
    entries:
    - title: 可用性
      url: "/concepts/sla-availability.html"
    - title: パフォーマンス
      url: "/concepts/sla-performance.html"
    - title: 持続可能性
      url: "/concepts/sla-sustainability.html"
    - title: ランサムウェアリカバリ保証
      url: "/concepts/sla-ransomware.html"
  - title: Keystone（プライベートモード）
    entries:
    - title: 概要
      url: "/dark-sites/overview.html"
    - title: 設置を準備
      url: "/dark-sites/requirements.html"
    - title: Keystone Collectorをインストールします
      url: "/dark-sites/install-collector.html"
    - title: Keystoneコレクタを設定する
      url: "/dark-sites/configure-collector.html"
    - title: Keystone Collectorの健全性を監視する
      url: "/dark-sites/monitor.html"
  - title: Digital Advisor REST APIからKeystoneにアクセス
    entries:
    - title: Digital Advisor REST APIを使用したKeystoneデータの取得を開始する
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: 更新トークンとアクセストークンの生成
      url: "/rest-api/generate-tokens.html"
    - title: Digital Advisor REST APIを使用しているすべてのお客様のリストを取得する
      url: "/rest-api/get-customer-list.html"
    - title: Digital Advisor REST APIを使用してお客様のサブスクリプションを取得
      url: "/rest-api/get-customer-subscriptions.html"
    - title: Digital Advisor REST APIを使用してお客様の消費情報を取得
      url: "/rest-api/get-customer-consumption.html"
  - title: 課金
    entries:
    - title: Keystoneの価格設定
      url: "/concepts/pricing.html"
    - title: コミット済み容量に基づく請求
      url: "/concepts/committed-capacity-billing.html"
    - title: 消費容量に基づく計測
      url: "/concepts/consumed-capacity-billing.html"
    - title: バースト消費に基づく請求
      url: "/concepts/burst-consumption-billing.html"
    - title: Keystone請求のその他のシナリオ
      url: "/concepts/misc-volume-billing.html"
    - title: 請求スケジュール
      url: "/concepts/billing-schedules.html"
  - title: Keystoneに関するサポートを受ける
    url: "/concepts/gssc.html"
  - title: 法的通知
    url: "/legal-notices.html"
