---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetAppは、Keystone STaaSサービスのリリースごとに新機能と強化された機能を提供します。 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone STaaS サービスの最新機能と拡張機能について学びます。



== 2025年10月6日



=== BlueXPはNetAppコンソールになりました

NetAppコンソールは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetAppデータ サービスの集中管理を提供し、リアルタイムの分析情報、ワークフローの高速化、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetAppコンソールのリリースノート"^] 。



== 2025年9月22日



=== アラート監視の追加

BlueXPのKeystoneダッシュボードには、サブスクリプション全体のアラートとモニターを管理するための *監視* タブが追加されました。この新しいタブでは次のことが可能になります。

* 容量使用状況とサブスクリプションの有効期限に関するシステム生成アラートとユーザー定義アラートの両方を含むアクティブなアラートを表示して解決します。
* 容量使用状況とサブスクリプション有効期限イベントを追跡するためのアラート モニターを作成します。


詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["アラートとモニターの表示と管理"] 。



=== 合理化されたパフォーマンス サービス レベルの表示

パフォーマンス サービス レベル情報は、別のタブから展開可能なビューに移動され、[*サブスクリプション*] タブ内で表示できます。各サブスクリプションの有効期限を表示するには、「*有効期限*」列の横にある下矢印をクリックします。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Keystoneサブスクリプションの詳細を表示する"] 。



== 2025年8月28日



=== 新しい列による論理使用状況の追跡の強化

FabricPoolボリュームのKeystone消費量追跡を強化するために、新しい列「合計フットプリント」が追加されました。

* * BlueXPのKeystoneダッシュボード *: *Assets* タブ内の *Volumes in clusters* タブに *Total footnotes* 列が表示されます。
* *Digital Advisor*: * ボリュームとオブジェクト * タブ内の * ボリュームの詳細 * タブに * 合計フットプリント * 列が表示されます。


この列には、パフォーマンス層とコールド層の両方のデータを含む、 FabricPool階層化を使用したボリュームの合計論理フットプリントが表示されるため、 Keystone の消費量を正確に計算できます。



== 2025年8月5日



=== インスタンスレベルの消費データを表示する

BlueXPのKeystoneダッシュボードを通じて、各パフォーマンス サービス レベル インスタンスの現在の消費量と履歴データを表示できます。この機能は、 Keystoneバージョン 3 (v3) サブスクリプションをお持ちの場合、複数のインスタンスのパフォーマンス サービス レベルで利用できます。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Keystoneサブスクリプションの消費量を表示する"] 。



== 2025年6月30日



=== Keystone バージョン 3 (v3) リリース

NetApp Keystone STaaS オファリングの最新リリースであるKeystoneバージョン 3 (v3) をサブスクライブできるようになりました。このバージョンでは、簡素化されたパフォーマンス サービス レベル、追加のバースト容量オプション、柔軟な課金頻度など、いくつかの機能強化が導入されています。これらの改善により、ストレージ ソリューションの管理、最適化、スケーリングが簡素化されます。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["v3 の Keystone STaaS サービス"] 。

Keystoneバージョン 3 (v3) をサブスクライブするには、 Keystoneサポート チームにお問い合わせください。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/concepts/gssc.html["Keystoneに関するサポートを受ける"] 。



== 2025年6月19日



=== BlueXPのKeystoneダッシュボード

BlueXPからKeystoneダッシュボードに直接アクセスできるようになりました。この統合により、すべてのKeystoneサブスクリプションとその他のNetAppサービスを一元的に監視、管理、追跡できるようになります。

BlueXP の Keystone ダッシュボードを使用すると、次のことが可能になります。

* すべてのサブスクリプションの詳細、容量の使用状況、資産を 1 か所で表示します。
* サブスクリプションを簡単に管理し、ニーズの変化に応じて変更をリクエストできます。
* ストレージ環境の最新情報を常に把握してください。


開始するには、BlueXP の左側のナビゲーション メニューで *ストレージ > Keystone* に移動します。詳細については、を参照して link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystoneダッシュボードの概要"]ください。



== 2025年1月8日



=== 日単位の累積データ使用量表示オプションの追加

請求済みデータを表示するバーをクリックすると、月単位または四半期単位の請求期間について、日単位の累積バーストデータ使用量をグラフ形式または表形式で表示できるようになりました。詳細については、を参照して link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["日単位のバーストデータ使用量を表示"]ください。



== 2024年12月12日



=== 名前が変更された論理使用列

[Volumes & Objects]*の*[Volume Details]*タブの*[Logical Used]*列の名前が*[Keystone Logical Used]*に変更されました。



=== 強化されたアセットタブ

[Keystone Subscriptions]画面の*[Assets]*タブに、* ONTAP *と* StorageGRID *という2つの新しいサブタブが追加されました。これらのサブタブには、ONTAPのクラスタレベルの詳細な情報と、サブスクリプションに基づくStorageGRIDのグリッドレベルの情報が表示されます。詳細については、を参照して link:./integrations/assets-tab.html["[Assets]タブ"^]ください。



=== 新しい[列の非表示/表示]オプション

[ボリュームとオブジェクト]*の*[ボリュームの詳細]*タブに*[列の表示/非表示]*オプションが追加されました。このオプションでは、列を選択または選択解除して、ボリュームの表形式のリストを希望に応じてカスタマイズできます。詳細については、を参照して link:./integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]ください。



== 2024年11月21日



=== 増額された累積バースト課金

四半期ごとの請求期間を選択している場合は、* Invoiced Accrued Burst *オプションを使用して、累積バースト使用量データを四半期ごとに表示できるようになりました。詳細については、を参照して link:./integrations/consumption-tab.html#view-accrued-burst["請求済みバースト容量の表示"^]ください。



=== [Volumes Details]タブの新しい列

論理使用量の計算をわかりやすくするために、*[ボリュームとオブジェクト]*タブ内の*[ボリュームの詳細]*タブに2つの新しい列が追加されました。

* *論理AFS *：ボリュームのアクティブファイルシステムで使用されている論理容量を表示します。
* *物理Snapshot *：Snapshotで使用されている物理スペースが表示されます。


これらの列は、* Logical Used *列をよりわかりやすく表示します。この列には、ボリュームのアクティブファイルシステムで使用されている論理容量とSnapshotで使用されている物理スペースの合計が表示されます。



== 2024年11月11日



=== レポート生成機能の強化

Digital Advisorのレポート機能を使用して、Keystoneデータの詳細を表示する統合レポートを生成できるようになりました。詳細については、 link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["統合レポートの生成"^] 。



== 2024年7月10日



=== ラベルの変更

ラベル* Current Usage *が* Current Consumption *に変更され、* Capacity Trend *が* Consumption Trend *に変更されます。



=== サブスクリプションの検索バー

[Keystone Subscriptions]画面のすべてのタブにある*[Subscriptions]*ドロップダウンに検索バーが表示されるようになりました。[サブスクリプション]*ドロップダウンにリストされている特定のサブスクリプションを検索できます。



== 2024年6月27日



=== サブスクリプションの一貫した表示

[Keystoneサブスクリプション]*画面が更新され、選択したサブスクリプション番号がすべてのタブに表示されます。

* [Keystoneサブスクリプション]*画面内のいずれかのタブが更新されると、画面は自動的に*[サブスクリプション]*タブに移動し、すべてのタブが*[サブスクリプション]*ドロップダウンに表示される最初のサブスクリプションにリセットされます。
* 選択したサブスクリプションがパフォーマンス指標にサブスクライブされていない場合、* Performance *タブには、ナビゲーション時に* Subscription *ドロップダウンにリストされた最初のサブスクリプションが表示されます。




== 2024年5月29日



=== エンハンスドバーストインジケータ

使用状況グラフインデックスの* Burst *インジケータが強化され、バースト制限のパーセンテージ値が表示されるようになりました。この値は、サブスクリプションで合意されたバースト制限に応じて変化します。また、* Usage Status *列の* Burst Usage *インジケーターにカーソルを合わせると、* Subscriptions *タブでバースト制限値を表示することもできます。



=== サービスレベルの追加

サービスレベル* CVO Primary *と* CVO Secondary *は、コミット済み容量がゼロのレートプランのサブスクリプション、またはメトロクラスタで構成されたサブスクリプションのCloud Volumes ONTAPをサポートするために含まれます。

* これらのサービスレベルの容量使用状況グラフは、* Keystone Subscriptions *ウィジェットと* Capacity Trend *タブの古いダッシュボードで確認できます。また、* Current Usage *タブの詳細な使用状況情報も確認できます。
* [サブスクリプション]タブでは、これらのサービスレベルは次のように表示されます。 `CVO (v2)` [Usage Type]列で、これらのサービスレベルに応じて課金を識別できます。




=== 短期間のバーストに対応したズームイン機能

[Capacity Trend]*タブにズームイン機能が追加され、使用状況グラフに短期的なバーストの詳細が表示されるようになりました。詳細については、を参照してください link:./integrations/consumption-tab.html["[Capacity Trend]タブ"^]。



=== サブスクリプションの表示の強化

サブスクリプションのデフォルト表示が拡張され、トラッキングIDでソートされるようになりました。*Subscriptions*タブのサブスクリプション（*Subscriptions*ドロップダウンおよびCSVレポートを含む）は、追跡IDのアルファベット順（a、a、b、Bなど）に基づいて表示されるようになりました。



=== 強化された累積バースト表示

[Capacity Trend]*タブの使用容量の棒グラフにカーソルを合わせると表示されるツールチップに、コミット済み容量に基づく累積バーストのタイプが表示されるようになりました。コミット済み容量レートプランがないサブスクリプションの場合は、暫定的な蓄積バーストと請求書による蓄積バーストを区別し、コミット済み容量がゼロの場合は*暫定的な蓄積消費*と*請求書による蓄積消費*、コミット済み容量がゼロでない場合は*暫定的な蓄積バースト*と*請求書による蓄積バースト*を表示します。



== 2024年5月9日



=== CSVレポートの新しい列

[Capacity Trend]*タブのCSVレポートに、* Subscription Number *列と* Account Name *列が追加され、詳細が改善されました。



=== Enhanced Usage Typeカラム

[サブスクリプション]タブ内の[使用タイプ]列が拡張され、論理的および物理的な使用状況が、ファイルとオブジェクトの両方のサービスレベルをカバーするサブスクリプションのカンマ区切り値として表示されます。



=== [Volume Details]タブからオブジェクトストレージの詳細にアクセス

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブに、オブジェクトストレージの詳細と、ファイルとオブジェクトの両方のサービスレベルを含むサブスクリプションのボリューム情報が表示されるようになりました。[ボリュームの詳細]*タブで*[オブジェクトストレージの詳細]*ボタンをクリックすると、詳細を確認できます。



== 2024年3月28日



=== [Volume Details]タブでのQoSポリシー準拠状況の表示の改善

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブで、サービス品質（QoS）ポリシーへの準拠がわかりやすく表示されるようになりました。以前は「* AQoS *」と呼ばれていた列の名前が「* Compliant *」に変更され、QoSポリシーが準拠しているかどうかが示されます。また、ポリシーが固定かアダプティブかを示す新しい列* QoSポリシータイプ*が追加されました。どちらも当てはまらない場合は、列に「_not available_」と表示されます。詳細については、を参照してください link:./integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Volume Summary（ボリュームサマリ）タブの新しい列と簡素化されたサブスクリプション表示

* [ボリュームとオブジェクト]タブの*[ボリュームの概要]*タブに、*[保護]*というタイトルの新しい列が追加されました。この列には、サブスクライブ済みのサービスレベルに関連付けられている保護されているボリュームの数が表示されます。保護されているボリュームの数をクリックすると*[ボリュームの詳細]*タブが表示され、保護されているボリュームのフィルタリングされたリストを確認できます。
* [Volume Summary]*タブが更新され、アドオンサービスを除く基本サブスクリプションのみが表示されるようになりました。詳細については、を参照してください link:./integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。




=== [Capacity Trend]タブの[Accrued burst]の詳細表示への変更

[Capacity Trend]*タブの容量使用率棒グラフにカーソルを合わせると表示されるツールチップには、その月の発生したバーストの詳細が表示されます。過去1カ月間の詳細は表示されません。



=== Keystoneサブスクリプションの履歴データを表示するためのアクセスの強化

Keystoneサブスクリプションが変更または更新された場合に履歴データを表示できるようになりました。サブスクリプションの開始日を前の日付に設定して、次の情報を表示できます。

* *容量傾向*タブからの消費量と累積バースト使用量データ。
* *パフォーマンス* タブからの ONTAP ボリュームのパフォーマンス メトリック。


データは、サブスクリプションの選択した開始日に基づいて表示されます。



== 2024年2月29日



=== [Assets]タブの追加

[Keystone Subscriptions]*画面に*[Assets]*タブが表示されるようになりました。この新しいタブには、サブスクリプションに基づいてクラスタレベルの情報が表示されます。詳細については、を参照してください link:./integrations/assets-tab.html["[Assets]タブ"^]。



=== [ボリュームとオブジェクト]タブの改善

ONTAPシステムボリュームをわかりやすくするために、*[ボリュームの概要]*と*[ボリュームの詳細]*という2つの新しいタブボタンが*[ボリューム]*タブに追加されました。[Volume Summary]*タブには、AQoS準拠ステータスや容量情報など、サブスクライブ済みのサービスレベルに関連付けられているボリュームの総数が表示されます。[ボリュームの詳細]*タブには、すべてのボリュームとその詳細が表示されます。詳細については、を参照してください link:./integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Digital Advisorでの検索機能の強化

Digital Advisor *画面の検索パラメータに、Keystoneサブスクリプション番号とKeystoneサブスクリプション用に作成された監視リストが表示されるようになりました。サブスクリプション番号または監視リスト名の最初の3文字を入力できます。詳細については、を参照してください link:./integrations/keystone-aiq.html["Active IQ Digital AdvisorでKeystoneダッシュボードを表示する"^]。



=== 消費データのタイムスタンプの表示

消費データのタイムスタンプ（UTC）は、* Keystone Subscriptions *ウィジェットの古いダッシュボードで確認できます。



== 2024年2月13日



=== プライマリサブスクリプションにリンクされているサブスクリプションを表示する機能

一部のプライマリサブスクリプションは、リンクされたセカンダリサブスクリプションを持つことができます。その場合、プライマリサブスクリプション番号は引き続き*サブスクリプション番号*列に表示され、リンクされたサブスクリプション番号は*サブスクリプション*タブの新しい列*リンクされたサブスクリプション番号*に表示されます。[リンクされたサブスクリプション]列は、リンクされたサブスクリプションがある場合にのみ使用可能になり、それらについて通知する情報メッセージが表示されます。



== 2024年1月11日



=== Accrued Burstに対して請求されたデータが返されました

[Capacity Trend]*タブの* Accrued Burst *のラベルが* Invoiced Accrued Burst *に変更されました。このオプションを選択すると、課金対象のバーストデータの月単位のグラフを表示できます。詳細については、を参照してください link:./integrations/consumption-tab.html#view-accrued-burst["請求済みバースト容量の表示"^]。



=== 特定の料金プランの発生した消費の詳細

_zero_committed容量のレートプランがあるサブスクリプションの場合は、* Capacity Trend *タブで消費量の詳細を確認できます。[Invoiced Accrued Consumption]*オプションを選択すると、課金されたAccrued Consumptionデータの月単位のグラフを表示できます。



== 2023年12月15日



=== 監視リストでの検索機能

Digital Advisorで監視リストのサポートが拡張され、Keystoneシステムも対象になりました。監視リストで検索して、複数のお客様のサブスクリプションの詳細を表示できるようになりました。Keystone STaaSでの監視リストの使用の詳細については、を参照してください link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Keystone監視リストで検索"^]。



=== UTCタイムゾーンに変換された日付

Digital Advisor の *Keystone サブスクリプション* 画面のタブに返されるデータは、UTC 時間 (サーバー タイムゾーン) で表示されます。クエリの日付を入力すると、自動的にUTC時間であると見なされます。詳細については、を参照してください link:./integrations/keystone-aiq.html["Keystoneサブスクリプションのダッシュボードとレポート"^]。
