---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Keystone STaaS サブスクリプションは、月ごと、四半期ごと、半年ごと、または年ごとに請求されます。 
---
= Keystoneの請求スケジュールについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS サブスクリプションは、月単位、四半期単位、半年単位、または年単位で請求されます。



== 月単位の課金

請求書は毎月送付されます。サービスが利用可能になった月については、請求書が翌月に送付されます。たとえば、 1 月に使用したサービスの請求書は、 2 月初めに送付されます。この請求書には、コミット済み容量の料金と、該当する場合はバースト時の使用料が含まれます。



== 四半期ごと、半年ごと、および年ごとの請求

四半期ごと、半年ごと、および年ごとの請求の場合、タイミングが若干異なるものの、プロセスは同様です。

* *四半期ごとの請求*：各サブスクリプション四半期の初めに、コミットされた容量の最低料金を記載した請求書が発行されます。また、バースト使用量が発生した場合は、四半期末に別の請求書が送信されます。
* *半年ごとの請求*: コミットされた容量の最低支払い額について、6 か月ごとに請求書が生成されます。バースト使用量が発生した場合、各四半期末に別の請求書が送信されます。
* *年次請求*: コミットされた容量の最低支払い額について、各サブスクリプション年の開始時に請求書が生成されます。バースト使用量が発生した場合、各四半期末に別の請求書が送信されます。


四半期ごと、半年ごと、および年ごとの請求の場合、サブスクリプション中にコミットされた容量が変更されると、そのサブスクリプション年の残りの期間の日割り計算された最低支払額の請求書が同じ日に送信されます。請求は、コミットされた容量の変更が有効になる日から計算されます。
