---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: インフラコンポーネント 
---
= 導入用のコンポーネント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、環境内でNetApp Keystone STaaSサービスを実現するために必要なコンポーネントを示します。



== サイト要件

スペース、ラック、PDU、電源など、サイト固有の要件がいくつかあります。 ここで説明した追加のネットワーク要件とセキュリティ要件に対応した冷却機能です。



=== スペース

Keystoneインフラ機器をホストするためのフロアスペース（お客様が用意）。ネットアップは、最終的な構成に基づいて重量仕様を提供します。



=== ラック

お客様が運用するサービスには、 4 柱式ラックが用意されています（お客様が用意）。ネットアップが提供するサービスでは、要件に応じて、ネットアップまたはお客様がラックを用意できます。ネットアップのディープラックは 42 個あります。



=== PDU

C13コンセントが十分にある、別々の保護された2つの回路に接続されたPower Distribution Unit（PDU；配電ユニット）を用意する必要があります。お客様が実施するサービスでは、場合によっては C19 コンセントが必要です。ネットアップが提供するサービスでは、要件に応じて、ネットアップまたはお客様がPDUを提供できます。



=== 電源

必要な電源を投入する必要があります。ネットアップでは、 200V 定格（標準 A 、最大 A 、標準 W 、最大 W 、電源コードタイプ、 および数量）。最終構成に基づきます。すべてのコンポーネントに冗長な電源装置があります。キャビネット内の電源コードはネットアップが提供します。



=== 冷却

ネットアップでは、最終的な構成と要件に基づいて、冷却要件の仕様（実効 BTU 、最大 BTU ）を提供しています。



=== Storage Virtual Machineの略

Keystoneサブスクリプションの監視と計測をサポートするには、Storage Virtual Machine（Storage VM）を以下のツールで導入する必要があります。KeystoneコレクタにはStorage VMが1つ必要です。OpsRamp GatewayにはStorage VMがもう1つ必要です

* Keystoneコレクタ-使用率指標の収集に使用：
+
** vCPU：4
** VRAM：16GB
** VDISK：200GB


* OpsRamp Gateway–ONTAP Keystone GSSCでリアルタイムモニタとリモートサポートに使用されます。
+
** vCPU：8
** VRAM：16GB
** VDISK：100GB






=== 導入オプション

Keystoneコレクタは、次の方法で導入できます。

* VMware OVAテンプレート（VMware vCenter Server 6.7以降が必要）
* お客様はRed Hat Enterprise Linux 7または8またはCentOS 7 Linuxサーバを提供し'Keystoneソフトウェアは'rpmのインストール・プロセスを介してインストールされます


OpsRamp Gatewayは次の構成に導入されます。

* VMware OVAテンプレート（VMware vCenter Server 6.7以降が必要）
* のブート可能な.isoインストーラです
+
** Citrix XenServer
** Microsoft Hyper-V
** Kernel-based Virtual Machine（Linux KVM）






=== ネットワーキング

Keystone CollectorおよびOpsRamp Gatewayの処理とメンテナンスには、アウトバウンドアクセスが必要です。

* support.netapp.com（使用状況データのアップロード）
* keystone.netapp.com（ソフトウェアアップデート）
* hub.docker.io（ソフトウェアアップデート）


お客様の要件や使用しているストレージコントローラによっては、ネットアップはお客様のサイトで10GB、40GB、100GBの接続を提供できます。

ネットアップは、ネットアップが提供するインフラデバイス専用に必要なトランシーバを提供します。お客様のデバイスに必要なトランシーバを提供し、ネットアップが提供するKeystoneインフラデバイスにケーブル接続する必要があります。



== リモートアクセスの要件

お客様のデータセンターまたはお客様が所有するコロケーションサービスとKeystoneオペレーションセンターにインストールされたストレージインフラ間では、ネットワーク接続が必要です。コンピューティングマシンと仮想マシン、およびインターネットサービスの提供は、顧客自身で行うネットワーク設計はセキュアなプロトコル経由で行う必要があり、ファイアウォールポリシーはネットアップとお客様の両方から承認されます。

ネットアップは、Keystoneのお客様に監視や課金などのサービスを提供するために、監視と管理のためにインストールされたハードウェアコンポーネントとソフトウェアコンポーネントにアクセスする必要があります。最も一般的な方法は、お客様のネットワークへの仮想プライベートネットワーク（VPN）接続を確立し、必要なデータにアクセスすることです。ファイアウォールポートのオープンから新しいサービスへの移行に伴う運用上の複雑さを解消するために、監視ツールは外部接続を開始します。OpsRampやZuoraなどのネットアップクラウドアプリケーションでは、この接続を使用して該当するサービスを実行します。この方法は、このサービスの一部である監視コンポーネントへのアクセスを提供しながら、ファイアウォールポートを開かないというお客様の要件を満たしています。
