---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: データ階層化アドオンサービスは、使用頻度の低いデータを特定し、サポート対象のストレージに階層化します。 
---
= Keystoneのデータ階層化アドオンサービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ファイルストレージとブロックストレージ向けのKeystone STaaS標準サービスには、使用頻度の低いデータを識別する階層化機能が含まれ、Keystone STaaS対応のネットアップコールドストレージに階層化できます。Keystone STaaSに対応したネットアップ以外の任意のストレージにコールドデータを階層化する場合は、アドオンサービスとしてデータ階層化を使用できます。

、link:../concepts/service-levels.html["Keystoneのパフォーマンスサービスレベル"] 。


NOTE: 階層化アドオン サービスは、Amazon Web Services (AWS) S3、Azure Blob、Google Cloud Platform (GCP)、その他のKeystone STaaS 対応、S3 互換、サードパーティ オブジェクト ストレージなど、 NetApp以外のストレージにデータを階層化する場合にのみ必要です。

階層化機能では、NetApp FabricPool テクノロジを利用して、オンプレミスとオフプレミスのオブジェクトストレージ階層に、アクセス頻度の低いデータを自動で階層化できます。

アドオン データ階層化サービスにより、Extreme、Premium、Performance、Standard、Value 層からオブジェクト ストレージ ターゲットへの階層化が可能になります。階層化されるホット データとコールド データの比率は固定されておらず、各階層は個別に計測され、請求されます。

たとえば、コールドストレージ階層のターゲットが次の場合です。

* Keystone STaaS Value 層、 Keystone STaaS StorageGRID Object 層、または既存のStorageGRID Webscale (SGWS) グリッド (顧客所有) - 追加料金はかかりません。これは標準サービスの一部です。
* パブリッククラウド（AWS、Azure、Google）やKeystone STaaSをサポートするサードパーティのオブジェクトストレージ-コールドストレージターゲットに階層化されたデータ容量には追加料金が発生します。


アドオン階層化サービスの料金は、サブスクリプション期間全体を通じて適用されます。


NOTE: Cloud Volumes ONTAPに必要なハイパースケーラーベースのコンピューティング、ストレージ、およびネットワーク サービスは、 Keystone STaaS サブスクリプションの一部としてNetAppによって提供されません。これらのサービスは、ハイパースケーラー クラウド サービス プロバイダーから直接調達する必要があります。

* 関連情報 *

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["ONTAP CLIを使用してデータ階層化（FabricPool）でKeystoneの消費量を概算する方法"^]
