---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: サポートが必要な場合は、NetApp Keystoneサポートチームにお問い合わせください。 
---
= Keystoneに関するサポートを受ける
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystoneサブスクリプションのサービスは、NetApp KeystoneサポートチームとKeystoneサクセスマネージャー（KSM）が担当します。サポートが必要な場合は、Keystoneサポートチームにお問い合わせください。



== NetApp Keystoneのサポート

ネットアップは、 NetApp Keystone のお客様に運用サービスをリモートで提供しています。これらのサービスには、ストレージ管理アクティビティ全体にわたる運用上のさまざまな分野が含まれます。これらのサービスには、アセットと構成の管理、容量とパフォーマンスの管理、変更管理、イベント、インシデントと問題の管理、サービスリクエストのフルフィルメント、レポートなどがあります。NetAppは、必要に応じてコントロールの状態と裏付けとなる証拠を示します。



== 追加情報

NetAppは、ITOM監視ソリューションを使用して、トラブルシューティングのためにNetApp Keystone環境をプロアクティブに監視し、接続します。


NOTE: パートナー運用モデルでは、テナントとサブテナントのサービス要求がパートナーのサービスデスクに割り当てられます。パートナーのサポートツールがITOMソリューションと統合されている場合があります。

Keystoneサービスの詳細については、以下を参照してください。

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* ネットアップの製品マニュアルhttps://docs.netapp.com["https://docs.netapp.com"^]




== Keystoneのサポート監視

NetApp Keystoneサポートは、製品とサブスクライブ済みサービスの健常性を監視し、リモートサポートを提供し、Keystoneサクセスマネージャーと連携します。

.Keystone Success Managerの略
Keystone Success Manager（KSM）は、Keystoneサービスに関してパートナー様と緊密に連携し、週単位または月単位の請求レポートや運用レポートを作成して更新します。責任は、NetApp Keystone 契約で規定されています。



== サービスリクエストを生成しています

オンボーディング時に、NetApp Keystone ServiceNowへのアクセスおよび使用のためのクレデンシャルが提供されている場合は、ポータルを使用して、Keystoneサブスクリプションに関連する問題に対するサービスリクエストを生成できます。

https://netappgssc.service-now.com/csm[]

サービスリクエストを作成する前に、システムの詳細、ログ、および関連情報を準備しておきます。サービスリクエストを発行すると、Keystoneサポートチームがサポートチケットを受け取り、トラブルシューティング用の情報にアクセスします。ServiceNowチケットをフォローして、ステータスと解決策を確認できます。

サポートバンドルの追加については、を参照してください link:../installation/monitor-health.html["サポートバンドルを生成して収集する"]。

エスカレーションが必要なオープンケース/チケットをお持ちの場合は、次のいずれかのアドレスに電子メールを送信してください：keystone.services@netapp.com keystone.escalations@netapp.com
