---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: NetApp Keystone STaaSサービスでは、指標の測定に複数の用語を使用しています。サービスのバージョン 3 で Keystone を使用する際には、これらの用語について詳しく理解しておく必要があります。 
---
= Keystoneで使用される指標と定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスでは、メトリックを測定するためにいくつかの用語を使用します。Keystoneを使用する際には、これらの用語についてさらに詳しく知る必要があるかもしれません。

Keystone STaaSサービスでは、指標を測定するために次の用語と定義が使用されます。

* 容量: GiB、TiB、PiB で測定されます。
* IOPS: 1 秒あたりに処理される入出力操作の数。
* サービスの可用性
* データの正確なアクセスの保持性
* レイテンシと速度




== メトリック測定

* *GiB、TiB、PiB での容量測定*: 1024 を基数としたデータ ストレージ容量の測定 (1 GiB = 1024^3^ バイト、1 TiB = 1024^4^ バイト、1 PiB = 1024^5^ バイト)。
* *IOPS での操作カウンター チャート*: アプリケーションによって要求された 1 秒あたりのプロトコル操作。
* *可用性*:サービスが正常に応答したI/O要求数の割合として、サービスに対して行われたI/O要求の総数で割った値。これは、1か月以内のサービス境界で測定され、顧客が提供する施設、ネットワーク、またはその他のサービスの予定されたサービスダウンタイムや利用不能は含まれません。
* *耐久性*：お客様が原因で行った削除や破損を除き、忠実性を損なうことなくアクセスされたデータの割合。
* * Latency *：クライアントから受信したI/O要求の処理にかかる時間。これはサービスの分離（ストレージコントローラのI/Oポート）で測定されます。




=== パフォーマンス指標

統合サービスおよびブロック最適化サービスには、次のパフォーマンス メトリックが適用されます。

*統合サービス:*

* *IOPS*: NFS を使用した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、読み取り比率 70%、書き込み比率 30%、ブロック サイズ 8 KB、レイテンシ 1 ミリ秒 (標準の場合は 4 ミリ秒) のランダム アクセスがサポートされます。
* *スループット*: NFS を使用した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、100% 読み取りと 32 KB のブロック サイズによるシーケンシャル アクセスがサポートされます。


*最適化されたサービスをブロックする:*

* *IOPS*: FCP を搭載した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、読み取り比率 70%、書き込み比率 30%、ブロック サイズ 8 KB、レイテンシ 1 ミリ秒のランダム アクセスがサポートされます。
* *スループット*: FCP を搭載した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスは、100% 読み取りと 64 KB のブロック サイズによるシーケンシャル アクセスをサポートします。

