---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: NetApp Keystone STaaSサービスでは、指標の測定に複数の用語を使用しています。Keystoneを使用する際には、これらの用語の詳細を確認することを推奨します。 
---
= Keystoneで使用される指標と定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaSサービスでは、指標の測定に複数の用語を使用しています。Keystoneを使用する際には、これらの用語の詳細を確認することを推奨します。

Keystone STaaSサービスでは、指標を測定するために次の用語と定義が使用されます。

* 容量の単位：GiB、TiB、PiB
* I/O密度：IOPS/TiB：ワークロードで消費される合計スペースのテビバイト単位で処理される1秒あたりの入出力処理数。
* サービスの可用性
* データの正確なアクセスの保持性
* レイテンシと速度




== メトリック測定

* *ギビバイト（GiB）、テビバイト（TiB）、およびピビバイト（PiB）での容量測定*：1024進数（1GiB = 1024^3^バイト、1TiB = 1024^4^バイト、1PiB = 1024^5^バイト）を使用したデータストレージ容量の測定値。
* * IOPS / TiB単位の処理カウンタグラフ：アプリケーションから要求された1秒あたりのプロトコル処理数を、ワークロードで使用されるボリュームのサイズで割った値。
* *可用性*:サービスが正常に応答したI/O要求数の割合として、サービスに対して行われたI/O要求の総数で割った値。これは、1か月以内のサービス境界で測定され、顧客が提供する施設、ネットワーク、またはその他のサービスの予定されたサービスダウンタイムや利用不能は含まれません。
* *耐久性*：お客様が原因で行った削除や破損を除き、忠実性を損なうことなくアクセスされたデータの割合。
* * Latency *：クライアントから受信したI/O要求の処理にかかる時間。これはサービスの分離（ストレージコントローラのI/Oポート）で測定されます。




=== スループットパフォーマンス指標

スループットパフォーマンス指標は、以下に基づくファイルサービスとブロックサービスにのみ適用されます。

* 32KBのブロックサイズ
* 70%読み取り/ 30%書き込みI/O構成




=== I/O密度の変化

IOPS / TiB、MBps / TiBで計算されるI/O密度は、次の要素によって異なります。

* ワークロードの特性
* レイテンシ。ただし、次のものは除きます。
+
** アプリケーションレイテンシ
** ホストのレイテンシ
** コントローラポートとの間でデータを転送する際のお客様のネットワークにおける遅延
** FabricPool の場合、オブジェクトストアへのデータ転送に伴うオーバーヘッドレイテンシ
** QoSによってレイテンシが自動的に適用され、I/Oがサービスレベルの最大値以内に維持されます


* 使用済み容量に含まれるユーザデータとSnapshotコピーデータ
* ボリューム内のデータ量に関係なく、各ONTAP ボリュームに割り当てられている絶対最小IOPS。
+
** 最高レベル：1、000 IOPS
** Premium：500IOPS
** Performance、Standard、Value：75 IOPS


* Advanced Data Protectionアドオンサービスの使用中は、ターゲットレイテンシはローカルストレージからのIO要求の処理にのみ適用されます。




=== ボリュームAQoS

各ONTAP に、適切なアダプティブQoSポリシーを適用する必要があります。ポリシーにAQoSポリシーが適用されていない各ボリューム内の容量には、最も高いサービスレベルの割合で課金されます。
