---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes 
summary: Keystoneの課金ルールは、特定のボリューム構成では異なります。このページでは、クローンボリューム、SnapMirrorデスティネーション、LUN、一時ボリューム、およびシステムボリュームの課金について説明します。 
---
= 特定のボリュームタイプに対するKeystone課金
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystoneの課金ルールは、特定のボリューム構成では異なります。これらの例外を知っておくと、クローンボリューム、SnapMirrorデスティネーション、LUN、または一時ストレージを操作する際に予期しない料金が発生するのを回避できます。

次の表は、各ボリュームタイプの課金ルールをまとめたものです。

[cols="1,2"]
|===
| ボリューム タイプ | 請求ルール 


| クローンボリューム | 標準ボリュームとして請求されます 


| 一時ボリューム | 請求なし 


| SnapMirror デスティネーション | 宛先のパフォーマンスサービスレベルで課金されます 


| LUN | 含まれるボリュームのパフォーマンスサービスレベルに基づいて課金されます 


| システムボリュームとルートボリューム | 監視されるが課金されない 
|===


== クローニングされたボリュームに対する請求

クローンされたボリュームは、クローン元のボリュームと同じパフォーマンスサービスレベルの標準ボリュームとして課金されます。クローンされたボリュームはすべて、そのサイズや用途に関わらず計測され、課金されます。



== 一時ボリュームについての請求

ボリュームを移動する際に、 ONTAP によって一時（ TMP ）ボリュームが作成されることがあります。これらの一時ボリュームは一時的なものであり、これらのボリュームの消費量は課金対象として測定されません。



== SnapMirror デスティネーションについての請求

SnapMirrorのデスティネーションボリュームの料金は、災害復旧用か長期保存用かを問わず、デスティネーションに割り当てられたパフォーマンスサービスレベルに基づいて決定されます。データ保護には追加料金はかかりません。



== LUN の請求

LUN の場合、課金はボリュームのパフォーマンス サービス レベルに基づいて行われます。



== システムボリュームとルートボリューム

システムボリュームとルートボリュームは、Keystoneサービスの全体的な監視の一環として監視されますが、カウントされたり課金されることはありません。これらのボリュームの消費は、請求から除外されます。
