---
sidebar: sidebar 
permalink: concepts/misc-volume-billing-v2.html 
keywords: Billing and miscellaneous scenarios 
summary: クローニングされたボリュームや高度なデータ保護など、特定の構成に対してKeystone料金を請求する方法をご紹介します。 
---
= Keystone請求のその他のシナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone バージョン2（v2）の特定の構成における課金について理解することで、サービス利用の最適化とコスト管理に役立ちます。対象となる構成には、クローンボリューム、高度なデータ保護、一時ボリューム、QoSポリシー、SnapMirrorの保存先、LUN、システム/ルートボリュームが含まれます。



== クローニングされたボリュームに対する請求

ONTAP でボリュームがクローニングされている場合に、データのバックアップとリストアに使用すると、追加の支払いなしでクローンを引き続き使用できます。ただし、ビジネスで他の目的に使用されていたクローンボリュームには、広範囲の期間料金がかかります。

次の点に注意してください。

* クローンボリュームは、サイズが親ボリュームの10%（親ボリュームで使用されている物理容量に対するクローンボリュームで使用されている物理容量）未満であれば充電されません。
* クローンボリュームには24時間の猶予期間はありません。クローンのサイズのみが考慮されます。
* クローンボリュームが親の物理サイズの10%を超えると、クローンは標準ボリューム（使用済み論理容量）として課金されます。




== 高度なデータ保護の課金

高度なデータ保護では、NetApp MetroClusterを使用して物理的に分離された2つのクラスタ間でデータをミラーリングMetroCluster のミラーされたアグリゲートの場合、データは各クラスタに1回ずつ、2回書き込まれます。Keystoneサービスでは、各サイドで個別に消費量が課金されるため、2つの同一の消費レコードが生成されます。アドオン料金は、データがソースにあるか、ミラーリングされているかまたはミラーリングされていないかに関係なく、サブスクリプション内のすべての容量に適用されます。

ONTAP System Manager（System Manager）またはActive IQ Unified Manager （Unified Manager）を使用してクラスタを監視する場合は、ツールとKeystoneで報告される使用量との間に不一致が生じることがあります。System ManagerとUnified Managerでは、ミラーリングされた（リモートの）クラスタにボリュームが報告されません。報告されるのは、Keystoneサービスから報告される消費指標の半分です。

.例
サイトAとサイトBは、MetroCluster 構成でセットアップされます。サイト A に 10TB のボリュームを作成すると、サイト B には同一の 10TB ボリュームが作成されますKeystoneは各サイトの消費量が10TBであることを確認し、合計で20TBの容量が増加しています。System ManagerとUnified Managerでは、サイトAに10TBのボリュームが作成されていると報告されますが、サイトBには10TBのボリュームは報告されません。

さらに、高度なデータ保護機能を備えたKeystoneシステムで作成されたボリュームは、それらのボリュームがミラーリングされているかどうかに関係なく、すべて高度なデータ保護の対象となります。



== 一時ボリュームについての請求

ボリュームを移動する際に、 ONTAP によって一時（ TMP ）ボリュームが作成されることがあります。これらの一時ボリュームは一時的なものであり、これらのボリュームの消費量は課金対象として測定されません。



== 課金およびアダプティブ QoS ポリシー

Keystoneは、サービスレベルに基づいて消費量を測定します。各サービスレベルは、特定のアダプティブQoSポリシーに関連付けられます。導入時に、サブスクリプションしたKeystoneサービスの各アダプティブQoSポリシーの詳細が通知されます。予期しない課金を回避するために、ストレージ管理処理の実行中は、サブスクライブしたサービスレベルごとに適切なアダプティブQoSポリシーがボリュームに割り当てられていることを確認してください。ONTAPのアダプティブQoSポリシーの詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"^]。



== SnapMirror デスティネーションについての請求

SnapMirrorデスティネーションボリュームの価格設定は、ソースで割り当てられたサービスレベルのアダプティブQoSポリシーによって管理されます。ただし、ソースにアダプティブQoSポリシーが関連付けられていない場合は、使用可能な最も低いサービスレベルに基づいてデスティネーションに課金されます。



== LUN の請求

LUNの場合は、アダプティブQoSポリシーで管理されるボリュームの場合と同じ課金パターンが適用されます。複数のLUNに別 々 のアダプティブQoSポリシーが設定されている場合：

* LUN のサイズは、その LUN に関連付けられているサービスレベルに基づいて消費されます。
* ボリューム内の残りのスペースがある場合は、そのボリュームで設定されているサービスレベルのアダプティブQoSポリシーに基づいて課金されます。




== システムボリュームとルートボリューム

システムボリュームとルートボリュームは、Keystoneサービスの全体的な監視の一環として監視されますが、カウントされたり課金されることはありません。これらのボリュームの消費は、請求から除外されます。
