---
sidebar: sidebar 
permalink: concepts/nrnvc.html 
keywords: Non-returnable, non-volatile components, SnapLock compliance, add-on service 
summary: NetAppは、NetApp Keystoneサブスクリプションの一部として、お客様のファイルサービス、ブロックサービス、オブジェクトサービス向けにNRNVCサービスを拡張します。 
---
= 返品不可、不揮発性コンポーネント、SnapLock準拠
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppは、NetApp Keystoneサブスクリプションの一部として、ファイルサービス、ブロックサービス、オブジェクトサービス向けに、返却不要不揮発性コンポーネント（NRNVC）サービスを拡張します。

ネットアップでは、サービスの提供中に使用された物理ストレージメディアをリカバリすることはありません。リカバリに使用されていた物理ストレージメディアは、ネットアップがリカバリの際にサービスの終了時にリカバリすることはありません。

Keystoneサブスクリプションの一部としてこのアドオンサービスをサブスクライブできます。このサービスを購入した場合は、次の点に注意してください。

* サービス期間の終了時や、ドライブや不揮発性メモリで障害が発生した場合やサービス期間中に欠陥が見つかった場合は、ドライブや不揮発性メモリを返却する必要はありません。
* ただし、ドライブや不揮発性メモリを破壊する証明書を作成する必要があり、それ以外の目的には使用できません。
* NRNVCに関連する追加コストは、サブスクリプションサービス全体（標準サービス、高度なデータ保護、データ階層化を含む）の月額料金に対する割合として課金されます。
* このサービスは、ファイル、ブロック、オブジェクトの各サービスにのみ適用されます。


標準サービスとクラウドサービスの詳細については、を参照してください link:supported-storage-services.html["Keystone STaaSサービス"]。

サービスレベルの詳細については、を参照してください link:../concepts/service-levels.html["Keystoneのサービスレベル"]。



== SnapLock コンプライアンス

SnapLock テクノロジは、ボリュームに設定された有効期限を過ぎたドライブを使用不可にすることで、NRNVC機能を有効にします。ボリュームでSnapLock テクノロジを使用するには、NRNVCに登録する必要があります。これは、ファイルサービスとブロックサービスにのみ該当します。

SnapLock テクノロジの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html["SnapLock とは"^]。
