---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystoneは、柔軟で拡張性に優れた消費ニーズに対応する従量課金制モデルを提供します。 
---
= Keystoneの価格について
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS の従量課金制サブスクリプション サービスは、ストレージ要件に合わせて予測可能な前払い価格設定により、柔軟でスケーラブルな消費を実現します。

Keystoneでは、次の請求機能を提供しています。

* さまざまなワークロードのニーズに合わせて、IOPS とレイテンシーのコミット容量に基づいて料金を支払うことができます。さまざまなパフォーマンス サービス ティア (Extreme、Premium、Standard、Value、Object、 Cloud Volumes ONTAP)により、購入したパフォーマンス サービス レベルに基づいてストレージを管理できます。
* また、容量の利用状況に応じて、コミット済み容量と従量課金制の容量を予測可能で提示します。
* ハードウェア、コア OS 、サポートのバンドル価格を 1TiB 価格で選択できます。ストレージ タイプ (統合、ブロック、最適化、オブジェクト、クラウド ストレージ サービス) ごとに 1 つの請求書が発行されます。
* サービス期間と支払いオプションは、月ごと、四半期ごと、半年ごと、年ごとなど、柔軟に選択できます。


Keystone請求は、コミット済み容量と可変バースト消費に基づいて行われます。

Keystoneでサポートされる各種容量については、を参照してください link:../concepts/supported-storage-capacity.html["Keystoneでサポートされるストレージ容量"]。

* 関連情報 *

* link:../concepts/committed-capacity-billing.html["コミット済み容量に基づく請求"]
* link:../concepts/consumed-capacity-billing.html["消費容量に基づく計測"]
* link:../concepts/burst-consumption-billing.html["バースト消費に基づく請求"]
* link:../concepts/misc-volume-billing.html["その他のボリュームタイプに基づく請求"]
* link:../concepts/billing-schedules.html["請求スケジュール"]

