---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystoneは、柔軟で拡張性に優れた消費ニーズに対応する従量課金制モデルを提供します。 
---
= Keystoneの価格設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
設備投資（CAPEX）やリースよりも運用コスト（OPEX）の消費モデルを希望される場合は、NetApp Keystone STaaSの従量課金制モデルを選択して、柔軟で拡張性に優れた消費モデルで、ストレージサブスクリプションの予測可能な初期料金を設定できます。

Keystoneには、以下の請求先施設が用意されています。

* IOPS とレイテンシのコミット済み容量に基づいて料金を支払うことで、さまざまなワークロードのニーズに対応できます。さまざまなパフォーマンスサービスレベル- Extreme、Premium、Performance、Standard、Value、 およびObjectを使用すると、購入したサービスレベルに基づいてストレージを管理できます。
* また、容量の利用状況に応じて、コミット済み容量と従量課金制の容量を予測可能で提示します。
* ハードウェア、コア OS 、サポートのバンドル価格を 1TiB 価格で選択できます。ストレージタイプ、ファイル、ブロック、オブジェクト、クラウドストレージの各サービスについて、 1 つの請求書を用意しておきます。
* サービスと支払いの柔軟な条件を選択します。サイトごとに12カ月、25TiB、またはそれ以上を選択できます。その後、12カ月間自動更新を実行できます。


Keystone請求は、コミット済み容量と可変バースト消費に基づいて行われます。

Keystoneでサポートされる各種容量については、を参照してください link:../concepts/supported-storage-capacity.html["Keystoneでサポートされるストレージ容量"]。

* 関連情報 *

* link:../concepts/committed-capacity-billing.html["コミット済み容量に基づく請求"]
* link:../concepts/consumed-capacity-billing.html["消費容量に基づく計測"]
* link:../concepts/burst-consumption-billing.html["バースト消費に基づく請求"]
* link:../concepts/misc-volume-billing.html["その他のボリュームタイプに基づく請求"]
* link:../concepts/billing-schedules.html["請求スケジュール"]

