---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystoneのサービス品質 
---
= Keystoneのサービス品質（QoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ストレージQuality of Service（QoS；サービス品質）は、アプリケーションのパフォーマンスが安定し、予測可能な安定したものになるようにするための重要なテクノロジです。QoSが設定されていないと、複数のシステムのブートなど、特定のワークロードが一定期間リソース全体を消費し、他のワークロードに影響を与える可能性があります。QoSの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"^]。

QoSを適用することで、アプリケーションのパフォーマンスが常に安定します。NetApp ONTAP では、QoSのパラメータを天井から https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-ceilings-qos-max["最大QoS"^]、スループットの下限- https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-floors-qos-min["最小QoS"^]。QoS Maxは、ワークロードが達成できるIOPSまたはMBps、IOPS、MBpsの最大数です。一方、最小QoSでは、ワークロードのスループットが一定のIOPS、MBps、またはIOPSとMBpsを下回らないことが保証されます。



== アダプティブ QoS

アダプティブQoS（AQoS）は、QoSポリシーが自動的に適用されるため、KeystoneサービスでTB / GBあたりのIOPSが一定になるように設定されています。AQoSポリシーの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["アダプティブ QoS について"^]。

KeystoneにはAQoSポリシーが用意されており、クラスタの本番環境への移行後に設定できます。システムで作成済みで使用可能な正しいAQoSポリシーにすべてのボリュームが関連付けられていることを確認する必要があります。


NOTE: ボリュームにAQoSポリシーを正しく適用していない場合は、サブスクリプションに基づいて最高のサービスレベルで測定および課金されます。これにより、意図しないバースト料金が発生する可能性があります。



== アダプティブQoSポリシーグループの設定

アダプティブQoS（AQoS）ポリシーを設定して、スループットの上限や下限をボリュームサイズに自動的に拡張することができます。ポリシーを設定する場合は、次の点に注意してください。

* *ポリシーグループ名*：AQoSポリシーグループの名前。例： `Keystone_extreme`。
* * vserver *：SVMまたはStorage VM（Storage Virtual Machine）の名前。
* *想定IOPS *：パフォーマンスが保証されているかぎり、ONTAP が最小値として提供するTiBあたりのIOPS数。
* *ピークIOPS *：パフォーマンスが制限される前にボリュームで使用可能な最大IOPS / TiB。
* *想定IOPS割り当て*：このフィールドは、ボリュームで使用可能な想定IOPSが、割り当てられたサイズと使用済みのサイズのどちらに基づいているかを制御します。Keystoneでは、割り当てられたスペースに基づいて判断します。
* *ピークIOPS割り当て*：このフィールドは、ボリュームに使用可能なピークIOPSが、割り当てられたサイズと使用済みのサイズのどちらに基づいているかを制御します。Keystoneでは、使用済みスペースに基づいて判断します。
* *絶対最小IOPS *：ボリュームサイズが非常に小さく、それ以外の場合に許容できない数のIOPSが発生する場合に、ボリュームに適用される想定IOPSの最小値。のデフォルト値は1、000です `Extreme`の場合は500 `Premium`の場合は250です `Performance`では75です `Standard` および `Value` サービスレベル：
+

NOTE: これはIOPS密度ではなく（75IOPS/TBなど）、絶対最小IOPS数です。



I/O密度の詳細については、を参照してください link:../concepts/metrics.html["Keystoneサービスで使用される指標と定義"]。AQoSポリシーグループの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["アダプティブ QoS ポリシーグループを使用する"^]。



== アダプティブQoSポリシーの設定

以降のセクションでは、各サービスレベルのアダプティブQoS（AQoS）ポリシーの設定について説明します。ここで指定するサービスレベルごとの最小ボリュームサイズと最大ボリュームサイズにより、ボリュームのIOPSとレイテンシの値を最適化できます。このガイドライン以外でボリュームを大量に作成すると、ボリュームのパフォーマンスが低下する可能性があります。



=== Extremeサービスレベルの設定

Extremeサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 最小ボリュームサイズ：100GiB、0.1TiB
* 最大ボリュームサイズ：10TiB




=== Premiumサービスレベルの設定

Premiumサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：50TiB




=== パフォーマンスサービスレベルの設定

パフォーマンスサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：80TiB




=== Standardサービスレベルの設定

Standardサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小ボリュームサイズ：1TiB
* 最大ボリュームサイズ：100TiB




=== 値サービスレベルの設定

値サービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小ボリュームサイズ：1TiB
* 最大ボリュームサイズ：100TiB




== ブロックサイズの計算

以下の設定を使用してブロックサイズを計算する前に、以下の点に注意してください。

* IOPS/TB = MBps / TiBをブロックサイズ* 1024で割った値
* ブロックサイズはKB/IO形式です
* TiB = 1024GiB、GiB = 1024MiB、MiB = 1024KiB、KiB = 1024Bytes、基本2あたり
* TB = 1000GB、GB = 1000MB、MB = 1000KB、KB = 1000Bytes、1進数の10になります


.ブロック・サイズの計算例
サービス・レベル（例：Extreme）のスループットを計算するには'次の手順を実行します

* 最大IOPS：12、288
* I/Oあたりのブロックサイズ：32KB
* 最大スループット=（12288 * 32 * 1024）/（1024 * 1024）= 384MBps / TiB


ボリュームの論理使用データが700GiBの場合、使用可能なスループットは次のようになります。

最大スループット= 384 * 0.7 = 268.8MBps
