---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: KeystoneはストレージQoSを使用して、アプリケーションの予測可能な一貫したパフォーマンスを確保します。 
---
= KeystoneのストレージQoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystoneは、ストレージQuality of Service（QoS；サービス品質）を使用して、アプリケーションが一貫した予測可能なパフォーマンスを得られるようにします。QoSを設定しないと、複数のシステムのブートなど、特定のワークロードが一定期間リソースのほとんどまたはすべてを消費し、他のワークロードに影響を与える可能性があります。

QoSの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"^]。



== アダプティブ QoS

アダプティブQoS（AQoS）は、ボリュームサイズに基づいてTiBあたりのIOPSを動的に維持するためにKeystoneサービスで使用されます。AQoSポリシーの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["アダプティブ QoS について"^]。

KeystoneにはAQoSポリシーが用意されており、クラスタの本番環境への移行後に設定できます。システムで作成済みで使用可能な正しいAQoSポリシーにすべてのボリュームが関連付けられていることを確認する必要があります。

ONTAP ボリュームにAQoSポリシーが適用されていない場合、そのボリュームは非準拠です。QoSポリシーが設定されていないボリュームは、使用可能な入出力処理を提供する優先度リストの最後になります。ただし、使用可能な入出力操作がある場合、ボリュームは使用可能なすべてのIOを消費する可能性があります。


NOTE: ボリュームにAQoSポリシーを適用していない場合、それらのボリュームは、サブスクリプションに基づいて最高のサービスレベルで測定および課金されます。これにより、意図しないバースト料金が発生する可能性があります。



== アダプティブQoSの設定

アダプティブQoS（AQoS）の設定はサービスレベルによって異なります。

|===


| *ポリシー名* | * エクストリーム * | * プレミアム * | * パフォーマンス * | * 標準 * | * 値 * 


| *想定IOPS * | 6,144 | 2 、 048 | 1,024 | 256 | 64 


| *想定IOPS割り当て* 5+| 割り当て済みスペース 


| *最大IOPS * | 12,288 | 4,096 | 2 、 048 | 512 | 128 


| *最大IOPS割り当て* 5+| 使用済みスペース 


| * ブロックサイズ * 5+| 32K 
|===


== アダプティブQoSポリシーグループの設定

アダプティブQoS（AQoS）ポリシーを設定して、スループットの上限や下限をボリュームサイズに自動的に拡張することができます。KeystoneのすべてのサービスレベルがデフォルトのONTAP QoSポリシーに準拠しているわけではありません。カスタムのQoSポリシーを作成できます。ポリシーを設定する場合は、次の点に注意してください。

* *ポリシーグループ名*：AQoSポリシーグループの名前。例： `Keystone_extreme`。
* * vserver *：SVMまたはStorage VM（Storage Virtual Machine）の名前。
* *想定IOPS *：十分なシステムIOPSがある場合にシステムが提供を試みる、ボリュームあたりの割り当て済みTiBあたりの最小IOPS。
* *ピークIOPS *：ボリュームがレイテンシの注入によってIOPSを調整するまでに許容される、ボリュームあたりの使用TiBあたりの最大IOPS。
* *想定IOPSの割り当て*：このパラメータは、ボリュームで使用可能な想定IOPSを、ボリュームの割り当てサイズまたは使用済みサイズに基づいて決定するかどうかを制御します。Keystoneでは、割り当てられたスペースに基づいて判断します。
* * Peak IOPS allocation *：このパラメータは、ボリュームで使用可能なピークIOPSを、ボリュームの割り当て済みサイズと使用済みサイズのどちらに基づいて設定するかを制御します。Keystoneでは、使用済みスペースに基づいて判断します。
* *絶対最小IOPS *：ボリュームサイズが非常に小さく、それ以外の場合に許容できない数のIOPSが発生する場合に、ボリュームに適用される想定IOPSの最小値。のデフォルト値は1、000です `Extreme`の場合は500 `Premium`の場合は250です `Performance`では75です `Standard` および `Value` サービスレベル：
+

NOTE: これはIOPS密度ではなく（75IOPS/TBなど）、絶対最小IOPS数です。



I/O密度の詳細については、を参照してください link:../concepts/metrics.html["Keystoneサービスで使用される指標と定義"]。AQoSポリシーグループの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["アダプティブ QoS ポリシーグループを使用する"^]。



== アダプティブQoSポリシーの設定

以降のセクションでは、各サービスレベルのアダプティブQoS（AQoS）ポリシーの設定について説明します。ここで指定するサービスレベルごとの最小ボリュームサイズと最大ボリュームサイズにより、ボリュームのIOPSとレイテンシの値を最適化できます。このガイドライン以外でボリュームを大量に作成すると、ボリュームのパフォーマンスが低下する可能性があります。



=== Extremeサービスレベルの設定

Extremeサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 最小ボリュームサイズ：100GiB、0.1TiB
* 最大ボリュームサイズ：10TiB




=== Premiumサービスレベルの設定

Premiumサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：50TiB




=== パフォーマンスサービスレベルの設定

パフォーマンスサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：80TiB




=== Standardサービスレベルの設定

Standardサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小ボリュームサイズ：1TiB
* 最大ボリュームサイズ：100TiB




=== 値サービスレベルの設定

値サービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小ボリュームサイズ：1TiB
* 最大ボリュームサイズ：100TiB




== ブロックサイズの計算

以下の設定を使用してブロックサイズを計算する前に、以下の点に注意してください。

* IOPS/TB = MBps / TiBをブロックサイズ* 1024で割った値
* ブロックサイズはKB/IO形式です
* TiB = 1024GiB、GiB = 1024MiB、MiB = 1024KiB、KiB = 1024Bytes、基本2あたり
* TB = 1000GB、GB = 1000MB、MB = 1000KB、KB = 1000Bytes、1進数の10になります


.ブロック・サイズの計算例
サービスレベルのスループットを計算する場合（例： `Extreme` サービスレベル：

* 最大IOPS：12、288
* I/Oあたりのブロックサイズ：32KB
* 最大スループット=（12288 * 32 * 1024）/（1024 * 1024）= 384MBps / TiB


ボリュームの論理使用データが700GiBの場合、使用可能なスループットは次のようになります。

最大スループット= 384 * 0.7 = 268.8MBps
