---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystoneのサービス品質 
---
= Keystoneのサービス品質（QoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ストレージQuality of Service（QoS；サービス品質）は、アプリケーションのパフォーマンスが安定し、予測可能な安定したものになるようにするための重要なテクノロジです。QoSが設定されていないと、複数のシステムのブートなど、特定のワークロードが一定期間リソース全体を消費し、他のワークロードに影響を与える可能性があります。QoSの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"]。

QoSを適用することで、アプリケーションのパフォーマンスが常に安定します。NetApp ONTAP では、QoS上限の2つのパラメータを定義しています。 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-ceilings-qos-max["最大QoS"]、スループットの下限- https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-floors-qos-min["最小QoS"]。QoS Maxは、ワークロードが達成できるIOPSまたはMBps、IOPS、MBpsの最大数です。一方、最小QoSは、ワークロードのスループットが特定のIOPS / MBps、またはIOPS / MBps未満でないことを保証します。



== アダプティブ QoS

アダプティブQoSは、QoSポリシーが自動的に適用されるため、KeystoneサービスでTBまたはGBあたりのIOPSの比率が一定になるように設定されます。アダプティブQoSについては、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["アダプティブ QoS について"]。

Keystoneには、クラスタが本番環境になった時点で設定可能なアダプティブQoSポリシーが用意されています。システムですでに作成されて使用可能な正しいアダプティブQoSポリシーがすべてのボリュームに関連付けられていることを確認してください。


NOTE: ボリュームにアダプティブQoSポリシーが正しく適用されていない場合、適用したボリュームはサブスクリプションごとに最も高いサービスレベルで測定されて課金されます。これにより、意図しないバースト料金が発生する可能性があります。



== アダプティブQoSポリシーグループの設定

アダプティブQoSポリシーは、スループットの上限や下限をボリュームサイズに自動的に調整するように設定できます。ポリシーを設定する場合は、次の点に注意してください。

* Policy Group name：アダプティブQoSポリシーグループの名前。たとえば'Keystone _extremeとなります
* Vserver：SVMまたはStorage VM（Storage Virtual Machine）の名前。
* 想定IOPS：パフォーマンスが保証されるかぎり最小値としてONTAP が提供するTiBあたりのIOPS数。
* 最大IOPS。パフォーマンスが制限される前にボリュームで使用可能な最大IOPS / TiB。
* 想定IOPS割り当て：割り当てスペースと使用済みスペースのどちらが想定IOPSか。このフィールドは、ボリュームで使用可能な想定IOPSが、ボリュームのプロビジョニング済みサイズと使用済みサイズのどちらに基づいているかを制御します。Keystoneでは、QoSの計算はすべて使用済みスペースに基づいて行われます。
* ピークIOPSの割り当て：割り当てスペースと使用済みスペースのどちらがピークIOPSを考慮するか。このフィールドは、ボリュームで利用可能なピークIOPSが、ボリュームのプロビジョニング済みサイズと使用済みサイズのどちらに基づいているかを制御します。Keystoneでは、QoSの計算はすべて使用済みスペースに基づいて行われます。
* 絶対最小IOPS：ボリュームサイズが非常に小さく、それ以外の場合に許容できない数のIOPSが発生する場合に、ボリュームに適用される想定IOPSの最小値。デフォルト値は'Extremeの場合は1,000 ' Premiumの場合は500 'その他のサービス・レベルの場合は75です
+

NOTE: これはIOPS密度ではなく（75IOPS/TBなど）、絶対最小IOPS数です。



詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["アダプティブ QoS ポリシーグループを使用する"]。



== アダプティブQoSポリシーの設定

アダプティブQoSポリシーの設定はサービスレベルごとに異なります。



=== Extremeサービスレベルの設定

Extremeサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation used-space -peak-iops-allocation used-space -block-size 32K
....
* 最小ボリュームサイズ：100GiB、0.1TiB
* 最大ボリュームサイズ：10TiB




=== Premiumサービスレベルの設定

 Settings and commands for the Premium service level:
* コマンド例：


....
qos adaptive-policy-group create -policy group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation used-space -peak-iops-allocation used-space -block-size 32K
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：50TiB




=== パフォーマンスサービスレベルの設定

パフォーマンスサービスレベルの設定とコマンド：

* コマンド例：


....
qos adaptive-policy-group create -policy group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation used-space -peak-iops-allocation used-space -block-size 32K
....
* 最小ボリュームサイズ：500GiB、0.5TiB
* 最大ボリュームサイズ：80TiB




=== 値サービスレベルの設定

 Settings and commands for the Value  service level:
* コマンド例：


....
qos adaptive-policy-group create -policy group <Keystone_premium> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation used-space -peak-iops-allocation used-space -block-size 32K
....
* 最小ボリュームサイズ：1TiB
* 最大ボリュームサイズ：100TiB




=== ボリュームサイズの推奨事項

ここで説明する各サービスレベルの最小ボリュームサイズと最大ボリュームサイズにより、ボリュームのIOPSとレイテンシの値が最適化されます。このガイドライン以外でボリュームを大量に作成すると、ボリュームのパフォーマンスが低下する可能性があります。



== ブロックサイズの計算

以下の設定を使用してブロックサイズを計算する前に、以下の点に注意してください。

* IOPS/TB = MBps / TiBをブロックサイズ* 1024で割った値
* ブロックサイズはKB/IO形式です
* TiB = 1024GiB、GiB = 1024MiB、MiB = 1024KiB、KiB = 1024Bytes、基本2あたり
* TB = 1000GB、GB = 1000MB、MB = 1000KB、KB = 1000Bytes、1進数の10になります


.ブロック・サイズの計算例
サービス・レベル（例：Extreme）のスループットを計算するには'次の手順を実行します

* 最大IOPS：12、288
* I/Oあたりのブロックサイズ：32KB
* 最大スループット=（12288 * 32 * 1024）/（1024 * 1024）= 384MBps / TiB


ボリュームの論理使用データが700GiBの場合、使用可能なスループットは次のようになります。

最大スループット= 384 * 0.7 = 268.8MBps
