---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaSは、事前定義されたサービスレベルでストレージ容量を提供します。Keystoneで管理される各ボリュームには、1つのサービスレベルが関連付けられています。 
---
= Keystoneのサービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaSは、事前定義されたパフォーマンスサービスレベルでデータストレージ容量を提供します。Keystoneサービスで管理される各ボリュームには、1つのサービスレベルが関連付けられます。

1つのサブスクリプションに複数の料金プランを設定でき、各料金プランは1つのサービスレベルに対応しています。各レートプランには、サービスレベルごとにコミット済み容量があります。

各サービスレベルは、I/O密度（IOPS/TiB/ボリューム）で定義されます。パフォーマンス（1秒あたりの入出力処理数[IOPS]）と使用済みストレージ容量（TiB）の比率で、ボリュームあたりの平均レイテンシでのIOPS/TiBです。

サービスレベルは、ストレージ環境、およびストレージと消費のニーズに基づいて選択します。基本サービスレベルはデフォルトで選択できます。アドオンサービスを選択した場合は、特定のサービスレベルも追加で選択できます。たとえば、Advanced Data Protectionアドオンサービスの場合、_Advanced Data-Protect_serviceレベルがサブスクリプションに割り当てられます。


TIP: NetApp Keystone STaaSサービスレベル向けの詳細なサービス概要を提供 https://www.netapp.com/services/keystone/terms-and-conditions/["こちらをご覧ください"^]。

以降のセクションでは、サポートされるストレージタイプ、ファイルサービス、ブロックサービス、オブジェクトサービス、クラウドサービスの基本サービスレベルについて説明します。



== ファイルストレージとブロックストレージのサービスレベル

* サポートされているプロトコル * ： NFS 、 CIFS 、 iSCSI 、 FC

|===


| * サービスレベル * | * エクストリーム * | * プレミアム * | * パフォーマンス * | * 標準 * | * 値 * 


| *ワークロードタイプの例* | 分析、データベース、ミッションクリティカルなアプリケーション | VDI、VSI、ソフトウェア開発 | OLTP、OLAP、コンテナ、ソフトウェア開発 | ファイル共有、 Web サーバ | バックアップ 


| *ボリュームあたりの最大IOPS /論理ティアBの格納数* | 12,288 | 4,096 | 2 、 048 | 512 | 128 


| *ボリュームあたりの割り当て済み論理容量（TiB）あたりの最大IOPS * | 6,144 | 2 、 048 | 1,024 | 256 | 64 


| *ボリュームあたりの最大MBps /論理TiB（32K B/Sの場合）* | 384 | 128 | 64 | 16 | 4. 


| *目標の90^th^パーセンタイルレイテンシ* | 1ミリ秒未満 | 2ミリ秒未満 | 4ミリ秒未満 | 4ミリ秒未満 | 17ミリ秒未満 


| *ブロックサイズ* 5+| 32K 
|===


=== ファイルストレージとブロックストレージのサービスレベルについて詳しく説明します

基本のサービスレベルメトリックは、次の条件によって異なります。

* ファイルストレージとブロックストレージのサービスレベルはONTAP 9.7以降をサポートします。
* サービスレベルのIOPS/TiB/ボリューム、MBPS/TiB/ボリューム、およびレイテンシの値は、ボリュームに格納されているデータの量、32KBのブロックサイズ、およびランダムI/O処理の70%と30%の書き込みI/O処理の組み合わせに基づきます。
* 実際のIOPS/TiB/ボリュームとMBPS/TiB/ボリュームは、実際のブロックサイズまたは想定されるブロックサイズ、システムワークロードの同時実行数、または入出力処理によって変わります。
* レイテンシには、次の要素は含まれません。
+
** アプリケーションまたはホストのレイテンシ
** コントローラポートとの間のお客様のネットワークレイテンシ
** FabricPool の場合のオブジェクトストアへのデータ転送に関連するオーバーヘッド
** レイテンシはQoSによって自動的に適用され、IOがサービスレベルの上限内に維持されます


* レイテンシの値は、MetroCluster 書き込み処理には適用されません。これらの書き込み処理は、リモートシステムの距離に依存します。
* ストレージシステム上の1つ以上のボリュームにAQoSポリシーが割り当てられていない場合、それらのボリュームは非準拠ボリュームとみなされ、それらのシステムに適用されるターゲットサービスレベルはありません。
* 想定IOPS_は、階層化ポリシーが「none」に設定されていて、ブロックがクラウドにない場合にのみFabricPool のターゲットになります。想定IOPS_は、SnapMirror同期関係にないボリュームを対象としています。
* Keystoneの順序で決定されるように、導入されているすべてのコントローラ間でワークロードIO処理を分散させる必要があります。




== オブジェクトストレージ

* サポートされるプロトコル * ： S3

|===


| * サービスレベル * | オブジェクト 


| * ワークロードタイプ * | メディアリポジトリ、アーカイブ 


| *ボリュームあたりの最大IOPS /論理TiB保存容量* | 該当なし 


| *ボリュームあたりの最大MBps /論理TiBの格納* | 該当なし 


| *平均レイテンシー* | 該当なし 
|===

NOTE: レイテンシには、FabricPool ストレージの場合、オブジェクトストアへのデータ転送に伴うオーバーヘッドは含まれません。



== クラウドストレージ

*サポートされるプロトコル*：NFS、CIFS、iSCSI、S3（AWSおよびAzureのみ）

|===


| * サービスレベル * | Cloud Volumes ONTAP 


| * ワークロードタイプ * | ディザスタリカバリ、ソフトウェア開発/テスト、ビジネスアプリケーション 


| *ボリュームあたりの最大IOPS /論理TiB保存容量* | 該当なし 


| *ボリュームあたりの最大MBps /論理TiBの格納* | 該当なし 


| *平均レイテンシー* | 該当なし 
|===
[NOTE]
====
* コンピューティング、ストレージ、ネットワーキングなどのクラウドネイティブサービスの料金は、クラウドプロバイダから請求されます。
* これらのサービスは、クラウドストレージとコンピューティングの特性によって異なります。


====
* 関連情報 *

* link:../concepts/supported-storage-capacity.html["サポートされているストレージ容量"]
* link:..//concepts/metrics.html["Keystoneサービスで使用される指標と定義"]
* link:../concepts/qos.html["Keystoneのサービス品質（QoS"]
* link:../concepts/pricing.html["Keystoneの価格設定"]

