---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS バージョン 3 は、事前定義されたサービス レベルでストレージ容量を提供します。Keystoneで管理される各ボリュームには、1つのサービスレベルが関連付けられています。 
---
= Keystoneのパフォーマンスサービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS バージョン 3 (v3) は、事前定義されたパフォーマンス サービス レベルでデータ ストレージ容量を提供します。Keystone サービスによって管理される各ボリュームには、パフォーマンス サービス レベルが関連付けられています。

サブスクリプションには複数の料金プランがあり、各料金プランはパフォーマンスサービスレベルに対応しています。各料金プランには、パフォーマンスサービスレベルごとにコミットされた容量があります。

パフォーマンス・サービスレベルには複数のインスタンスが存在する場合があり、各インスタンスは、お客様の環境においてそのパフォーマンス・サービスレベルに割り当てられた個別のストレージアレイを表します。各パフォーマンス・サービスレベルは、1秒あたりの入出力操作数（IOPS）、スループット（GBps）、およびレイテンシ（ms）によって定義され、これらの指標はパフォーマンス・サービスレベル・インスタンスごとに測定・適用されます。

ストレージ環境、ストレージおよび消費のニーズに基づいて、パフォーマンス サービス レベルを選択します。基本パフォーマンス サービス レベルはデフォルトで利用できます。アドオン サービスを選択した場合は、特定のパフォーマンス サービス レベルも追加で利用できます。


TIP: NetApp Keystone STaaSパフォーマンスサービスレベルの詳細なサービス説明は入手可能です。  https://www.netapp.com/services/keystone/terms-and-conditions/["こちらをご覧ください"^] 。

サポートされているストレージ タイプ (統合、ブロック最適化、オブジェクト、クラウド サービス) の基本パフォーマンス サービス レベルについては、次のセクションで説明します。



== 統合ストレージのパフォーマンス サービス レベル

*サポートされているプロトコル*: FC、iSCSI、NFS、NFSv4/RDMA、NVMe/FC、NVMe/TCP、SMB、S3

|===


| *パフォーマンス サービス レベル* (パフォーマンス サービス レベル インスタンスごとのすべての仕様) | * エクストリーム * | * プレミアム * | * 標準 * | * 値 * 


| *ワークロードタイプの例* | AI/ML、HPC、インメモリ DB | 分析、EDA、OLTP | OLAP、IoT、コンテナ | バックアップ、アーカイブ 


| *最大IOPS*^1^ | 100万 | 550K | 500K | NA 


| *最大GBps* | 40 | 20 | 20 | NA 


| *目標の90^th^パーセンタイルレイテンシ* | 1ミリ秒未満 | 1ミリ秒未満 | <=4 ミリ秒 | >4ミリ秒 


| *最小コミット済み容量* | 50TiB | 50TiB | 100TiB | 100TiB 


| *コミット容量の増分増加* 4+| 25TiB 


| *コミット済み容量と従量課金容量のタイプ* 4+| 論理的または物理的 
|===


== ブロック最適化ストレージのパフォーマンス サービス レベル

*サポートされているプロトコル*: NVMe/TCP、NVMe/FC、FC、iSCSI

|===


| *パフォーマンス サービス レベル* (パフォーマンス サービス レベル インスタンスごとのすべての仕様) | * エクストリーム * | * プレミアム * 


| *ワークロードタイプの例* 2+| SAP HANA、Oracle、MS SQL Server、EPIC 


| *最大IOPS*^1^ | 850K | 450K 


| *最大GBps* | 65 | 25 


| *目標の90^th^パーセンタイルレイテンシ* | 1ミリ秒未満 | 1ミリ秒未満 


| *最小コミット済み容量* | 50TiB | 50TiB 


| *コミット容量の増分増加* 2+| 25TiB 


| *コミット済み容量と従量課金容量のタイプ* 2+| 論理的または物理的 
|===

NOTE: ^1^相互に排他的な目標。実際のパフォーマンスは、オペレーティング システムのバージョン、ハードウェア、ワークロードの種類、同時操作の数など、さまざまな要因によって異なる場合があります。



=== 統合ストレージとブロック最適化ストレージのパフォーマンス サービス レベルの詳細

基本パフォーマンス サービス レベル メトリックは、次の条件によって異なります。

* パフォーマンス サービス レベルは ONTAP 9.8 以降をサポートします。
* 統合ストレージの場合、
+
** *IOPS*: NFS を使用した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、読み取り比率 70%、書き込み比率 30%、ブロック サイズ 8 KB、レイテンシ 1 ミリ秒 (標準の場合は 4 ミリ秒) のランダム アクセスがサポートされます。
** *スループット*: NFS を使用した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、100% 読み取りと 32 KB のブロック サイズによるシーケンシャル アクセスがサポートされます。


* ブロック最適化ストレージの場合、
+
** *IOPS*: FCP を搭載した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスでは、読み取り比率 70%、書き込み比率 30%、ブロック サイズ 8 KB、レイテンシ 1 ミリ秒のランダム アクセスがサポートされます。
** *スループット*: FCP を搭載した ONTAP 9.16.1 の場合、各パフォーマンス レベルのインスタンスは、100% 読み取りと 64 KB のブロック サイズによるシーケンシャル アクセスをサポートします。


* レイテンシには、次の要素は含まれません。
+
** アプリケーションまたはホストのレイテンシ
** コントローラポートとの間のお客様のネットワークレイテンシ
** FabricPool の場合のオブジェクトストアへのデータ転送に関連するオーバーヘッド


* レイテンシの値は、MetroCluster 書き込み処理には適用されません。これらの書き込み処理は、リモートシステムの距離に依存します。
* 想定IOPS_は、階層化ポリシーが「none」に設定されていて、ブロックがクラウドにない場合にのみFabricPool のターゲットになります。想定IOPS_は、SnapMirror同期関係にないボリュームを対象としています。




== オブジェクトストレージのパフォーマンスサービスレベル

* サポートされるプロトコル * ： S3

|===


| *パフォーマンスサービスレベル* | * 標準 * | * 値 * 


| *注文あたりの最小コミット容量* | 200TiB | 500TiB 


| *コミット容量の増分増加* | 25TiB | 100TiB 


| *コミット済み容量と従量課金容量のタイプ* 2+| 物理 
|===


== クラウドストレージ

*サポートされているプロトコル*: NFS、CIFS、iSCSI、S3 (AWS および Azure のみ)

|===


| *パフォーマンスサービスレベル* | Cloud Volumes ONTAP 


| *注文あたりの最小コミット容量* | 4TiB 未満 


| *コミット容量の増分増加* | 1TiB 


| *コミット済み容量と従量課金容量のタイプ* | 論理 
|===
[NOTE]
====
* コンピューティング、ストレージ、ネットワーキングなどのクラウドネイティブサービスの料金は、クラウドプロバイダから請求されます。
* これらのサービスは、クラウドストレージとコンピューティングの特性によって異なります。


====
* 関連情報 *

* link:../concepts/supported-storage-capacity.html["サポートされているストレージ容量"]
* link:..//concepts/metrics.html["Keystoneサービスで使用される指標と定義"]
* link:../concepts/pricing.html["Keystoneの価格設定"]

