---
sidebar: sidebar 
permalink: concepts/service-levels-v2.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaSは、事前定義されたサービスレベルでストレージ容量を提供します。Keystoneで管理される各ボリュームには、1つのサービスレベルが関連付けられています。 
---
= Keystoneのパフォーマンスサービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS バージョン 2 (v2) は、事前定義されたパフォーマンス サービス レベルでデータ ストレージ容量を提供します。Keystone サービスによって管理される各ボリュームには、パフォーマンス サービス レベルが関連付けられています。

サブスクリプションには複数の料金プランがあり、各料金プランはパフォーマンスサービスレベルに対応しています。各料金プランには、パフォーマンスサービスレベルごとにコミットされた容量があります。

各パフォーマンス サービス レベルは、I/O 密度 (IOPS/TiB/ボリューム) によって定義されます。パフォーマンス（1秒あたりの入出力処理数[IOPS]）と使用済みストレージ容量（TiB）の比率で、ボリュームあたりの平均レイテンシでのIOPS/TiBです。

ストレージ環境、ストレージ容量、消費量のニーズに応じて、パフォーマンス・サービス・レベルを選択してください。基本パフォーマンス・サービス・レベルはデフォルトでご利用いただけます。アドオンサービスをご利用の場合は、特定のパフォーマンス・サービス・レベルもご利用いただけます。例えば、高度なデータ保護アドオンサービスの場合、サブスクリプションには「Advanced Data-Protect」パフォーマンス・サービス・レベルが割り当てられます。


TIP: NetApp Keystone STaaSパフォーマンスサービスレベルの詳細なサービス説明は入手可能です。  https://www.netapp.com/services/keystone/terms-and-conditions/["こちらをご覧ください"^] 。

サポートされているストレージ タイプ (ファイル、ブロック、オブジェクト、クラウド サービス) の基本パフォーマンス サービス レベルについては、次のセクションで説明します。



== ファイルおよびブロックストレージのパフォーマンス サービス レベル

* サポートされているプロトコル * ： NFS 、 CIFS 、 iSCSI 、 FC

|===


| *パフォーマンスサービスレベル* | * エクストリーム * | * プレミアム * | * パフォーマンス * | * 標準 * | * 値 * 


| *ワークロードタイプの例* | 分析、データベース、ミッションクリティカルなアプリケーション | VDI、VSI、ソフトウェア開発 | OLTP、OLAP、コンテナ、ソフトウェア開発 | ファイル共有、 Web サーバ | バックアップ 


| *ボリュームあたりの最大IOPS /論理ティアBの格納数* | 12,288 | 4,096 | 2 、 048 | 512 | 128 


| *ボリュームあたりの割り当て済み論理容量（TiB）あたりの最大IOPS * | 6,144 | 2 、 048 | 1,024 | 256 | 64 


| *ボリュームあたりの最大MBps /論理TiB（32K B/Sの場合）* | 384 | 128 | 64 | 16 | 4. 


| *目標の90^th^パーセンタイルレイテンシ* | 1ミリ秒未満 | 2ミリ秒未満 | 4ミリ秒未満 | 4ミリ秒未満 | 17ミリ秒未満 


| *ブロックサイズ* 5+| 32K 


| *コミット済み容量と従量課金容量のタイプ* 5+| 論理 
|===


=== ファイルおよびブロックストレージのパフォーマンスサービスレベルの詳細

基本パフォーマンス サービス レベル メトリックは、次の条件によって異なります。

* ファイルおよびブロック ストレージのパフォーマンス サービス レベルは、ONTAP 9.7 以降をサポートします。
* パフォーマンス サービス レベルの IOPS/TiB/ボリューム、MBps/TiB/ボリューム、およびレイテンシ値は、ボリュームに保存されるデータの量、32 KB のブロック サイズ、および 70% の読み取り IO 操作と 30% の書き込み IO 操作のランダムな組み合わせに基づいています。
* 実際のIOPS/TiB/ボリュームとMBPS/TiB/ボリュームは、実際のブロックサイズまたは想定されるブロックサイズ、システムワークロードの同時実行数、または入出力処理によって変わります。
* レイテンシには、次の要素は含まれません。
+
** アプリケーションまたはホストのレイテンシ
** コントローラポートとの間のお客様のネットワークレイテンシ
** FabricPool の場合のオブジェクトストアへのデータ転送に関連するオーバーヘッド
** IO をパフォーマンス サービス レベルの最大値内に維持するために QoS によって自動的に適用される遅延


* レイテンシの値は、MetroCluster 書き込み処理には適用されません。これらの書き込み処理は、リモートシステムの距離に依存します。
* ストレージ システム上の 1 つ以上のボリュームに AQoS ポリシーが割り当てられていない場合、これらのボリュームは非準拠ボリュームと見なされ、これらのシステムにはターゲット パフォーマンス サービス レベルは適用されません。
* 想定IOPS_は、階層化ポリシーが「none」に設定されていて、ブロックがクラウドにない場合にのみFabricPool のターゲットになります。想定IOPS_は、SnapMirror同期関係にないボリュームを対象としています。
* Keystoneの順序で決定されるように、導入されているすべてのコントローラ間でワークロードIO処理を分散させる必要があります。




== オブジェクトストレージ

* サポートされるプロトコル * ： S3

|===


| *パフォーマンスサービスレベル* | オブジェクト 


| * ワークロードタイプ * | メディアリポジトリ、アーカイブ 


| *ボリュームあたりの最大IOPS /論理TiB保存容量* | 該当なし 


| *ボリュームあたりの最大MBps /論理TiBの格納* | 該当なし 


| *平均レイテンシー* | 該当なし 


| *コミット済み容量と従量課金容量のタイプ* | 物理 
|===

NOTE: レイテンシには、FabricPool ストレージの場合、オブジェクトストアへのデータ転送に伴うオーバーヘッドは含まれません。



== クラウドストレージ

*サポートされるプロトコル*：NFS、CIFS、iSCSI、S3（AWSおよびAzureのみ）

|===


| *パフォーマンスサービスレベル* | Cloud Volumes ONTAP 


| * ワークロードタイプ * | ディザスタリカバリ、ソフトウェア開発/テスト、ビジネスアプリケーション 


| *ボリュームあたりの最大IOPS /論理TiB保存容量* | 該当なし 


| *ボリュームあたりの最大MBps /論理TiBの格納* | 該当なし 


| *平均レイテンシー* | 該当なし 
|===
[NOTE]
====
* コンピューティング、ストレージ、ネットワーキングなどのクラウドネイティブサービスの料金は、クラウドプロバイダから請求されます。
* これらのサービスは、クラウドストレージとコンピューティングの特性によって異なります。


====
* 関連情報 *

* link:../concepts/supported-storage-capacity-v2.html["サポートされているストレージ容量"]
* link:..//concepts/metrics-v2.html["Keystoneサービスで使用される指標と定義"]
* link:../concepts/qos.html["Keystoneのサービス品質（QoS"]
* link:../concepts/pricing-v2.html["Keystoneの価格設定"]

