---
sidebar: sidebar 
permalink: concepts/sla-ransomware.html 
keywords: ransomware, recovery, guarantee, SLA, Keystone, assurance 
summary: NetAppは、ランサムウェア攻撃が発生した場合に、Ransomware Recovery Guaranteeプログラムを使用して、SnapLock ComplianceボリュームからSnapshotデータをリカバリすることを保証します。 
---
= ランサムウェアリカバリ保証
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppは、ランサムウェア攻撃が発生した場合に、Ransomware Recovery Guaranteeプログラムを使用して、SnapLock ComplianceボリュームからSnapshotデータをリカバリすることを保証します。NetApp Ransomware Recovery Assurance Serviceは、Ransomware Recovery保証プログラムをサポートするために必要であり、関連するKeystone注文とは別に購入する必要がある。



== サービスレベル

Ransomware Recovery Assurance Serviceは、該当するサブスクリプション期間中、Keystoneサブスクリプションをサポートするすべてのハードウェアに対して必要である。



== サービスクレジット

SnapLock Complianceがベストプラクティスに従って導入され、Ransomware Recovery Assuranceサービスの購入時にNetAppプロフェッショナルサービスが設定または検証を行った場合、SnapLockで保護されているデータがリカバリできない場合、NetAppはサービスクレジットを発行します。これらのクレジットの基準は次のとおりです。

* サービスクレジットは、今後の請求書に適用できます。クレジットは、Committed Contract Value（CCV）の10%に制限され、サブスクリプション単位で支払われます。
* クレジットは、関連するKeystone注文のアクティブなサブスクリプション期間中に提供される。
* 月額課金制のサブスクリプションの場合、クレジットは今後12カ月間に分割され、サブスクリプション期間が終了するまでKeystoneの今後の請求書に使用できる。サブスクリプションが12カ月以内に終了した場合は、更新してクレジットを引き続き使用することも、クレジットを他のNetApp請求書に適用することもできます。
* 年間サブスクリプションの場合、クレジットはKeystoneの次の請求書（利用可能な場合）に適用されます。今後Keystoneの請求書がない場合は、クレジットを他のNetAppの請求書に適用できます。

