---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS サービス バージョン 3 でサポートされるストレージ容量の種類について説明します。 
---
= Keystoneでサポートされるストレージ容量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスは、いくつかの種類のストレージ容量をサポートしています。これらのさまざまな容量用語を理解しておくと、 Keystoneを使用するときに役立ちます。



== 論理容量

これは、ストレージ アレイによって提供されるデータ効率が適用される前に、ユーザー データを格納するために必要なストレージ容量の量です。



== コミット済み容量

サブスクリプション中に毎月請求される最小論理容量：

* 容量は各パフォーマンス サービス レベルに割り当てられます。
* 期間中にコミット容量と追加のパフォーマンス サービス レベルを追加できます。




=== コミット済み容量に対する変更

サブスクリプションの期間中に、コミット済み容量を変更できます。ただし、前提条件は次のとおりです。

* コミット済み容量は、特定の条件に基づいて削減できます。詳細については、を参照してください link:../concepts/capacity-requirements.html["容量の削減"]。
* サブスクリプションをさらに12カ月延長する場合を除き、サブスクリプションの有効期限の90日前にコミット済み容量を増やすことはできません。
* コミットされた容量の変更は、コンソールまたはKeystone Success Manager (KSM) からリクエストできます。変更のリクエストについては、以下を参照してください。link:../concepts/gssc.html["NetApp Keystoneのサポート"] 。




== 使用済み容量

使用済み容量は、サービスで現在消費されている容量（TiB単位のストレージ）です。ストレージタイプに応じて計算方法が異なります。

* *統合ストレージまたはブロック最適化ストレージ*: 消費容量は、注文プロセス中に選択された容量のタイプ (論理または物理) に基づいて計算されます。計算はパフォーマンス サービス レベル インスタンスごとに実行されます。
+
.. *論理容量*: 次の合計です:
+
*** ストレージ アレイのデータ効率化前の、コピー、ミラー コピー、バージョン、クローンなど、顧客データのすべてのインスタンスとタイプを保存するための測定された論理容量。
*** スナップショットおよび特定のクローンのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。


.. *身体能力*: 次の合計です:
+
*** ストレージ アレイのデータ効率を考慮した後、コピー、ミラー コピー、バージョン、クローンなど、顧客データのすべてのインスタンスとタイプを保存するための測定された物理容量。
*** スナップショットのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。




* *オブジェクトストレージ*：消費容量は、すべてのノードにわたるすべてのインスタンスと顧客データのタイプを保存するために使用された、計測された物理容量として計算されます。この計算は、設定された情報ライフサイクル管理（ILM）ポリシーに基づいています。
* *Cloud Volumes ONTAP*: 消費容量は、すべての Cloud Volumes ONTAP ボリュームの計測されたプロビジョニング容量として計算されます。




== バースト時の容量

NetApp Keystone STaaSサービスでは、コミットされた容量に加えて、パフォーマンス・サービスレベルに応じた追加容量を利用できます。これはバースト容量使用と呼ばれます。

次の点に注意してください。

* バースト時の容量は、Keystone契約で合意されます。これは通常、パフォーマンス サービス レベル インスタンスごとにコミットされた容量の 20% 超に設定され、コミットされた容量の 40% または 60% のバースト容量制限を選択するための追加オプションも利用できます。
* バースト容量の消費量は、選択したパフォーマンス サービス レベルに対応するコミット容量と同じ料金で請求されます。
* Keystone STaaS サービスでは、開始日から 60 日間のバースト免除期間が提供されます。




== 請求容量

月次請求 = （コミット済み容量 [TiB ] * コミット率 [TiB / TiB ] ） + （日単位の平均プロビジョニングバースト容量 [TiB ] * バーストレート [TiB / TiB ] ）月単位の課金には、コミット済み容量に基づく最小料金が含まれます。

月単位の請求額は、日単位の平均バースト容量の消費量に基づいて、最小料金を超えます。
