---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaSサービスでサポートされるストレージ容量のタイプについて説明します。 
---
= Keystoneでサポートされるストレージ容量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaSサービスは、複数のタイプのストレージ容量をサポートします。これらの容量のさまざまな用語を理解しておくと、Keystoneを利用する際に役立ちます。



== 論理容量

これは、お客様がKeystoneインフラに配置したデータです。Keystoneのすべての容量は論理容量を表します。たとえば、1TiBのファイルがKeystoneインフラに格納された場合、最小容量1TiBを購入する必要があります。



== コミット済み容量

サブスクリプション中に毎月請求される最小論理容量：

* 容量は各サービスレベルにコミットされます。
* コミット済み容量および追加のサービスレベルは、期間中に追加できます。




=== コミット済み容量に対する変更

サブスクリプションの期間中に、コミット済み容量を変更できます。ただし、前提条件は次のとおりです。

* コミット済み容量は、特定の条件に基づいて削減できます。詳細については、を参照してください link:../concepts/capacity-requirements.html["容量の削減"]。
* サブスクリプションをさらに12カ月延長する場合を除き、サブスクリプションの有効期限の90日前にコミット済み容量を増やすことはできません。
* 認定済み容量の変更は、BlueXPインターフェイスまたはKeystone Success Manager（KSM）を通じてリクエストできます。変更リクエストの詳細については、を参照してくださいlink:../concepts/gssc.html["NetApp Keystoneのサポート"]。




== 使用済み容量

使用済み容量は、サービスで現在消費されている容量（TiB単位のストレージ）です。これは次の合計です。

* すべてのインスタンスおよびタイプのユーザデータ（コピー、ミラーコピー、バージョンなど）の格納に使用される論理容量。
* 元のボリュームのサイズの10%を超えるクローンボリュームの格納に使用されている論理容量。
* Snapshotコピーから差分データを格納するために使用される物理容量。
* 割り当てられている物理容量。




== バースト時の容量

Keystoneサービスでは、コミット済み容量の上に追加の容量を確保し、サービスレベルを高めることができます。バースト時の容量使用量。次の点に注意してください。

* バースト時の容量は、Keystone契約で合意されます。この値は通常、コミット済み容量を20%上回るように設定され、コミット済み容量と同じ速度で充電されます。
* バースト時の容量は柔軟に消費でき、消費された平均値に対して1日単位で課金されます。




== 請求容量

月次請求 = （コミット済み容量 [TiB ] * コミット率 [TiB / TiB ] ） + （日単位の平均プロビジョニングバースト容量 [TiB ] * バーストレート [TiB / TiB ] ）月単位の課金には、コミット済み容量に基づく最小料金が含まれます。

月単位の請求額は、日単位の平均バースト容量の消費量に基づいて、最小料金を超えます。
