---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaSサービスは、ONTAPとStorageGRIDをサポートします。 
---
= Keystoneでサポートされるストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS サービスは、 NetAppの統合ストレージ、ブロック最適化ストレージ、オブジェクト ストレージ、およびCloud Volumes ONTAP をサポートします。

サポートされているストレージ オプションは次のとおりです。

* *統合ストレージ*: ファイル、ブロック、S3 オブジェクト ストレージの両方が含まれ、NetApp ONTAP AFF および FAS システムで利用できます。
* *ブロック最適化ストレージ*: NetApp ONTAP ASAシステムで利用可能なブロック ストレージが含まれます。
* *オブジェクト ストレージ*: NetApp StorageGRID システムで利用可能なオブジェクト ストレージが含まれます。


Keystone STaaSで、ストレージの標準的なサービスとオプションのサービスを提供します。

* Keystone STaaS標準サービス*：Standardサービスは基本サブスクリプションに含まれており、別途料金が発生することはありません。

* Keystone STaaSアドオンサービス*：このサービスはオプションで有料です。このサービスは、Keystone STaaS標準サブスクリプションサービスに加えて、追加のユーティリティとメリットを提供します。

Keystone STaaSサービスは同時にご利用いただけます。例えば、クラウドストレージのサブスクリプションは、統合ストレージ、ブロック最適化ストレージ、オブジェクトストレージのサブスクリプションと同じ期間でご利用いただけます。クラウドサービスは、既存のストレージサブスクリプションのサービス期間中いつでも含めることができます。ただし、既存の統合ストレージ、ブロック最適化ストレージ、またはオブジェクトストレージのサブスクリプションを更新する予定がない場合は、サブスクリプションの最後の90日間はクラウドストレージのサブスクリプションを追加できません。



== 統合、ブロック最適化、オブジェクトストレージ向けサービス

統合、ブロック最適化、オブジェクト ストレージ向けの Keystone STaaS サービスは、複数の機能とプロトコルをサポートしており、次の表で説明されています。

|===
| ストレージ | プラットフォーム | プロトコル | サポートされている機能 


 a| 
統合ストレージ
 a| 
ONTAP
 a| 
NFSとCIFS
 a| 
ONTAP Oneのすべての機能をサポート



 a| 
ブロック最適化ストレージ
 a| 
ONTAP
 a| 
FCおよびiSCSI
 a| 
ONTAP Oneのすべての機能をサポート



 a| 
オブジェクトストレージ
 a| 
StorageGRID
 a| 
S3
 a| 
ONTAP Oneのすべての機能をサポート

|===
ONTAP Oneの詳細については、 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAPライセンスの概要"^]そしてlink:https://www.netapp.com/blog/ontap-one/["ONTAP One: ONTAP のパワーをすべて 1 つに"^] 。



== クラウドストレージ向けサービス

Keystone STaaSがクラウドストレージサービスを提供Keystone STaaSは、Amazon Web Services（AWS）、Microsoft Azure、Google Cloud PlatformでCloud Volumes ONTAP のデータ管理機能をサポートします。


NOTE: Cloud Volumes ONTAP に必要なハイパースケーラベースのコンピューティング、ストレージ、ネットワークサービスは、Keystone STaaSサブスクリプションの一部としてネットアップから提供されるものではありません。これらのサブスクリプションは、ハイパースケーラークラウドサービスプロバイダから直接調達する必要があります。
