---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaSサービスは、ONTAPとStorageGRIDをサポートします。 
---
= Keystoneでサポートされるストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaSサービスは、ONTAP のファイルストレージとブロックストレージ、StorageGRID プラットフォームのオブジェクトストレージ、Cloud Volumes ONTAP のデータ管理機能をサポートします。

Keystone STaaSで、ストレージの標準的なサービスとオプションのサービスを提供します。

* Keystone STaaS標準サービス*：Standardサービスは基本サブスクリプションに含まれており、別途料金が発生することはありません。

* Keystone STaaSアドオンサービス*：このサービスはオプションで有料です。このサービスは、Keystone STaaS標準サブスクリプションサービスに加えて、追加のユーティリティとメリットを提供します。

Keystone STaaSサービスを相互に共存させることができます。たとえば、クラウドストレージサブスクリプションは、ファイル、ブロック、オブジェクトストレージのサブスクリプションと長期的な契約が可能です。クラウドサービスは、既存のストレージサブスクリプションのサービス期間中いつでも含めることができます。ただし、既存のファイル、ブロック、およびオブジェクトのサブスクリプションを更新しない場合は、サブスクリプションの過去90日間にクラウドストレージのサブスクリプションを追加することはできません。



== ファイル、ブロック、オブジェクトストレージ用のサービス

次の表に、ONTAP のファイル/ブロックストレージ、およびStorageGRID オブジェクトストレージ向けのKeystone STaaSサービスでは、複数の機能とプロトコルがサポートされます。

|===
| ストレージ | プラットフォーム | プロトコル | サポートされている機能 


 a| 
ファイルストレージ
 a| 
ONTAP
 a| 
NFSとCIFS
 a| 
サポートされるONTAP 機能：

* FlexVol
* FlexGroup
* Snapshot コピー
* SnapMirror（非同期）
* SnapVault
* SnapLock エンタープライズ
* FabricPoolとクラウドの階層化
* SnapRestore
* FlexClone
* SnapCenter （ライセンスは含まれていますが、Keystoneサービスには含まれていません。また、管理は保証されません）
* 自律型ランサムウェア対策^1^




 a| 
ブロックストレージ
 a| 
ONTAP
 a| 
FCおよびiSCSI
 a| 
サポートされるONTAP 機能：

* FlexVol
* FlexGroup
* Snapshot コピー
* SnapMirror（非同期）
* SnapVault
* SnapLock エンタープライズ
* FabricPoolとクラウドの階層化
* SnapRestore
* FlexClone
* SnapCenter （ライセンスは含まれていますが、Keystoneサービスには含まれていません。また、管理は保証されません）




 a| 
オブジェクトストレージ
 a| 
StorageGRID
 a| 
S3
 a| 
複数のサイトにわたって複数の情報ライフサイクル管理（ILM）ポリシーをサポート^2^

|===

NOTE: ^1^ ONTAPでのランサムウェア対策の詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自律的なランサムウェア防御"^]。
^2^各サイトには個別のサブスクリプションが必要です。



== クラウドストレージ向けサービス

Keystone STaaSがクラウドストレージサービスを提供Keystone STaaSは、Amazon Web Services（AWS）、Microsoft Azure、Google Cloud PlatformでCloud Volumes ONTAP のデータ管理機能をサポートします。


NOTE: Cloud Volumes ONTAP に必要なハイパースケーラベースのコンピューティング、ストレージ、ネットワークサービスは、Keystone STaaSサブスクリプションの一部としてネットアップから提供されるものではありません。これらのサブスクリプションは、ハイパースケーラークラウドサービスプロバイダから直接調達する必要があります。
