---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaSサービスは、ONTAPとStorageGRIDをサポートします。 
---
= Keystoneでサポートされるストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaSは、NetAppプラットフォームおよびCloud Volumes ONTAPで、統合ストレージ、ブロック最適化ストレージ、AFXストレージ、オブジェクトストレージをサポートしています。各ストレージタイプはデータストレージタイプ（DST）として定義され、基本サブスクリプションに含まれる標準サービスと、オプションの追加サービスで利用可能です。



== Keystone STaaSの標準サービスおよびアドオンサービス

Keystone STaaSで、ストレージの標準的なサービスとオプションのサービスを提供します。

* Keystone STaaS標準サービス*：Standardサービスは基本サブスクリプションに含まれており、別途料金が発生することはありません。

* Keystone STaaSアドオンサービス*：このサービスはオプションで有料です。このサービスは、Keystone STaaS標準サブスクリプションサービスに加えて、追加のユーティリティとメリットを提供します。

複数の Keystone STaaS サービスを同時にサブスクライブできます。クラウド サービスがサブスクリプションに追加されると、ユニファイド ストレージ、ブロック最適化ストレージ、オブジェクト ストレージと同じ期間を共有します。クラウド サービスは、アクティブなストレージ サブスクリプション期間中のいつでも追加できます。ただし、既存のユニファイド ストレージ、ブロック最適化ストレージ、またはオブジェクト ストレージのサブスクリプションを更新する予定がない場合、そのサブスクリプションの最後の 90 日間にクラウド サービスを追加することはできません。


NOTE: AFXサブスクリプションは単体で利用可能であり、同じサブスクリプション内で統合ストレージ、ブロック最適化ストレージ、またはオブジェクトストレージと組み合わせることはできません。AFXを他のストレージタイプと併用する必要がある場合は、それぞれを別々のサブスクリプションとして注文する必要があります。



== サポートされているデータ ストレージのタイプ

Keystone STaaSサービスは、統合ストレージ、ブロック最適化ストレージ、オブジェクトストレージ、およびAFXストレージに対応しており、複数の機能とプロトコルをサポートしています。詳細は以下の表をご覧ください。

|===
| データストレージのタイプ | 製品説明 | プラットフォーム | プロトコル | サポートされている機能 


 a| 
Unified
 a| 
ファイル、ブロック、S3 オブジェクト ストレージが含まれます
 a| 
AFFおよびFASシステム上のONTAP
 a| 
FC、iSCSI、NFS、NFSv4/RDMA、NVMe/FC、NVMe/TCP、SMB、S3
 a| 
ONTAP Oneのすべての機能をサポート



 a| 
ブロック最適化
 a| 
ブロック ストレージを含む
 a| 
NVMe/TCP、NVMe/FC、FC、iSCSI
 a| 
FCおよびiSCSI
 a| 
すべての ONTAP One for SAN 機能をサポート



 a| 
AFX
 a| 
分散型ストレージプラットフォーム上のファイルおよびオブジェクトストレージを含む
 a| 
AFX システムの ONTAP
 a| 
NFSv3、NFSv4/RDMA、pNFS、SMB、S3
 a| 
ONTAP Oneのすべての機能をサポート



 a| 
オブジェクト
 a| 
オブジェクト ストレージを含む
 a| 
StorageGRID
 a| 
S3
 a| 
すべての StorageGRID 機能をサポート

|===
ONTAP Oneの詳細については、 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAPライセンスの概要"^]そしてlink:https://www.netapp.com/blog/ontap-one/["ONTAP One: ONTAP のパワーをすべて 1 つに"^] 。



== クラウドストレージ向けサービス

Keystone STaaSがクラウドストレージサービスを提供Keystone STaaSは、Amazon Web Services（AWS）、Microsoft Azure、Google Cloud PlatformでCloud Volumes ONTAP のデータ管理機能をサポートします。


NOTE: Cloud Volumes ONTAP に必要なハイパースケーラーベースのコンピューティング、ストレージ、ネットワークサービスは、Keystone STaaS サブスクリプションの一部として NetApp から提供されません。これらのサブスクリプションは、ハイパースケーラーのクラウド サービス プロバイダーから直接調達する必要があります。
