---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS サービス バージョン 3 でサポートされるストレージ容量の種類について説明します。 
---
= Keystoneのストレージ容量タイプ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaSは、ストレージの計測、コミット、課金を行うために、いくつかの容量に関する用語を使用します。これらの用語を理解することで、サブスクリプションの計画や使用状況レポート、請求書の解釈に役立ちます。



== 論理容量

これは、ストレージ アレイによって提供されるデータ効率が適用される前に、ユーザー データを格納するために必要なストレージ容量の量です。



== コミット済み容量

サブスクリプション中に毎月請求される最小論理容量：

* 容量は、統合ストレージまたはブロック最適化ストレージの各パフォーマンス サービス レベル インスタンス、あるいは AFF クラスタごとに割り当てられます。
* 期間中にコミット容量と追加のパフォーマンス サービス レベルを追加できます。




=== コミット済み容量に対する変更

契約期間中は、一定の条件を満たせば、契約済みの容量を変更することができます。容量増加および減少ルールの詳細については、link:../concepts/capacity-requirements.html["Keystoneパフォーマンス サービス レベルの容量要件"]を参照してください。変更を依頼するには、Keystoneサクセスマネージャー（KSM）またはlink:../concepts/support-services.html["NetAppサポート"]にお問い合わせください。



== 使用済み容量

消費容量とは、サービス上で現在消費されているストレージ容量（TiB単位）を指します。データ保存タイプに基づいて計算方法が異なります：

* *統合ストレージまたはブロック最適化ストレージ*: 消費容量は、注文プロセス中に選択された容量のタイプ (論理または物理) に基づいて計算されます。計算はパフォーマンス サービス レベル インスタンスごとに実行されます。
+
.. *論理容量*: 次の合計です:
+
*** ストレージ アレイのデータ効率化前の、コピー、ミラー コピー、バージョン、クローンなど、顧客データのすべてのインスタンスとタイプを保存するための測定された論理容量。
*** スナップショットおよび特定のクローンのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。


.. *身体能力*: 次の合計です:
+
*** ストレージ アレイのデータ効率化後の、コピー、ミラー コピー、バージョン、クローンなど、お客様のデータのすべてのインスタンスとタイプを格納するための従量制物理容量。
*** スナップショットのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。




* *AFXストレージ*：AFXクラスタごとに、以下の合計として計算されます：
+
** ストレージ アレイのデータ効率化後の、コピー、ミラー コピー、バージョン、クローンなど、お客様のデータのすべてのインスタンスとタイプを格納するための従量制物理容量。
** スナップショットのメタデータと差分データを保存するために使用される物理容量。
** シックプロビジョニングされた物理容量。


* *オブジェクトストレージ*：消費容量は、すべてのノードにわたるすべてのインスタンスと顧客データのタイプを保存するために使用された、計測された物理容量として計算されます。この計算は、設定された情報ライフサイクル管理（ILM）ポリシーに基づいています。
* *Cloud Volumes ONTAP*：消費容量は、すべてのCloud Volumes ONTAPボリュームの計測済みプロビジョニング済み論理容量として計算されます。




== バースト時の容量

NetApp Keystone STaaSサービスでは、コミットされた容量に加えて、パフォーマンス・サービスレベルに応じた追加容量を利用できます。これはバースト容量使用と呼ばれます。

次の点に注意してください。

* バースト容量制限は、Keystone注文で合意されます。通常は、パフォーマンスサービスレベルのインスタンスごと、またはAFXクラスタごとに、コミット済み容量の20%増しにデフォルト値が設定されています。さらに、統合ストレージおよびブロック最適化ストレージでは、コミット済み容量の40%または60%のバースト容量制限を選択するオプションも利用可能です。
* バースト容量の消費量は、選択されたデータ ストレージ タイプ（DST）およびパフォーマンス サービス レベルに対応する、コミット済み容量と同じ料金で請求されます。
* Keystone STaaS サービスでは、開始日から 60 日間のバースト免除期間が提供されます。




== 請求容量

月次請求 = （コミット済み容量 [TiB ] * コミット率 [TiB / TiB ] ） + （日単位の平均プロビジョニングバースト容量 [TiB ] * バーストレート [TiB / TiB ] ）月単位の課金には、コミット済み容量に基づく最小料金が含まれます。

月単位の請求額は、日単位の平均バースト容量の消費量に基づいて、最小料金を超えます。
