---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: NetApp Support Siteを使用して、Keystoneサブスクリプションのサポートケースを作成したり、連絡先情報を確認したりできます。 
---
= Keystoneに関するサポートを受ける
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppは、Keystoneのお客様に運用サービスを提供します。お客様は、専用のKeystoneサクセスマネージャー（KSM）、直接サポートへの連絡オプション、およびITOMソリューションによるプロアクティブな監視を利用できます。



== NetAppサポートサービス

NetAppは、Keystoneのお客様に運用サービスをリモートで提供します。これらのサービスは、資産および構成管理、容量およびパフォーマンス管理、変更管理、イベントおよびインシデント管理、サービスリクエストの履行、レポート作成など、さまざまなストレージ管理アクティビティにわたります。

.Keystone Success Managerの略
KSMは、お客様のKeystoneサービスについてお客様と緊密に連携し、週次または月次の請求書および運用レポートを提供します。具体的な責任は、NetApp Keystone契約書に定義されています。



== サポートにお問い合わせください

Keystone サブスクリプションで問題が発生した場合は、 NSS クレデンシャルを使用してlink:https://support.netapp.com["NetAppサポート サイト"^]にログインし、サポートケースを作成してください。

NSSログインをお持ちでない場合は、link:https://mysupport.netapp.com/site/user/registration["アカウントを登録する"^]サブスクリプション内のいずれかのノードのシリアル番号（SN）を使用します。

スクリーンショット付きの手順については、link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["テクニカルサポートケースを開く方法"^]を参照してください。

サポート担当者と直接お話しになりたい場合は、以下のいずれかの番号にお電話ください：

* 米国／カナダ：888 463 8277
* ヨーロッパ：00 800 44 638277
* インド：000 800 100 8948
* その他の世界的なデータ：link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== サポートの監視

NetAppは、ITOM監視ソリューションを使用して、製品とサブスクライブサービスの健全性をプロアクティブに監視し、トラブルシューティングのためにNetApp Keystone環境に接続します。



== その他のリソース

Keystoneサービスの詳細については、以下を参照してください。

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["NetApp製品ドキュメント"^]


* 関連情報 *

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["ONTAPプラットフォームのシリアル番号を識別する方法"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["StorageGRID テクニカルサポートケースの作成時に使用するシリアル番号"^]

