---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: アドオン、追加サービスの詳細、データ階層化 
---
= データの階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ファイルストレージとブロックストレージ向けのKeystone STaaS標準サービスには、使用頻度の低いデータを識別する階層化機能が含まれ、Keystone STaaS対応のネットアップコールドストレージに階層化できます。コールドデータをKeystone STaaSでサポートされるネットアップ以外のストレージに階層化する場合は、アドオンサービスとしてデータ階層化を利用できます。

標準サービスとアドオンサービスについては、を参照してください link:../concepts/supported-storage-services.html["Keystone STaaSサービス"]。サービスレベルの詳細については、を参照してください link:../concepts/service-levels.html["Keystoneのサービスレベル"]。

階層化アドオンサービスが必要となるのは、データがAmazon Web Services（AWS）S3、Azure Blob、Google Cloud Platform（GCP）などのネットアップ以外のストレージに階層化されている場合のみです。Keystone STaaSをサポートし、S3互換性のある、サードパーティのオブジェクトストレージも必要です。

階層化機能では、NetApp FabricPool テクノロジを利用して、オンプレミスとオフプレミスのオブジェクトストレージ階層に、アクセス頻度の低いデータを自動で階層化できます。

アドオンのデータ階層化サービスでは、Extreme、Premium、Performance、Standard、Valueの各階層からオブジェクトストレージターゲットへの階層化が可能です。階層化されるホットコールドデータの比率は固定されず、各階層は個別に計測および請求されます。

たとえば、コールドストレージ階層のターゲットが次の場合です。

* Keystone STaaSの価値階層、Keystone STaaS StorageGRID オブジェクト階層、または既存のSGWSグリッド（お客様が所有）-追加料金なしで標準サービスに含まれます。
* パブリッククラウド（AWS、Azure、Google）やKeystone STaaSをサポートするサードパーティのオブジェクトストレージ-コールドストレージターゲットに階層化されたデータ容量には追加料金が発生します。


アドオン階層化サービスの料金は、サブスクリプション期間全体を通じて適用されます。


NOTE: Cloud Volumes ONTAP に必要なハイパースケーラベースのコンピューティング、ストレージ、ネットワークサービスは、Keystone STaaSサブスクリプションの一部としてネットアップから提供されるものではありません。これらのサービスはハイパースケーラークラウドサービスプロバイダから直接調達する必要があります。
