---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: アドオン、追加サービスの詳細、データ階層化 
---
= データの階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
デフォルトでは、Keystoneのベースサービスには、サブスクライブされているファイルサービスとブロックサービスによる階層化機能があります。この機能によって、使用頻度が低いデータを特定し、ネットアップが所有、導入、管理するコールドストレージに階層化します。コールドデータをエンタープライズクラウドストレージなどのネットアップ以外のストレージに階層化する場合は、アドオンサービスとして階層化することができます。

階層化アドオンサービスが必要となるのは、Amazon Web Services（AWS）S3、Azure Blob、Google Cloud Platform（GCP）などのネットアップ以外のストレージにデータが階層化されている場合と、サポートされているS3互換のサードパーティのオブジェクトストレージ以外にデータが階層化されている場合のみです。

ベースストレージとクラウドストレージサービスについては、を参照してください link:../concepts/supported-storage-services.html["サポートされているストレージサービス"]。

サービスレベルの詳細については、を参照してください link:../concepts/service-levels.html["Keystoneのサービスレベル"]。

この階層化機能では、 NetApp FabricPool テクノロジを活用して、オンプレミスまたはオフプレミスの低コストのオブジェクトストレージ階層へデータを自動で階層化できます。この機能により、アクセス頻度の低いデータは、合意したサービスに基づいて、オンプレミスまたはクラウドの低コストのストレージに自動的に階層化されます。

アドオンの階層化サービスでは、Extreme、Premium、Performance、Standard、Valueの各階層からオブジェクトターゲットへの階層化が可能です。ホットティアとコールドティアはメーター制で、個別に請求されます。

データの階層化は、価格を変更することなくいつでも追加でき、ホット/コールド比率の点で柔軟性が向上します。階層化されるホットなコールドデータの比率は固定されず、階層化された物理ブロックの数は別々に測定されます。

詳細については、次の計算を実行してください。

コールドストレージ階層のターゲットが次の場合：

* 値階層（最大500TiB）、オブジェクト階層（500TiB以上）、既存のSGWSグリッド（お客様が所有）–基本的なストレージサービスに含まれるため、追加料金は発生しません。
* パブリッククラウド（AWS、Azure、Google）およびその他のサードパーティがサポートするオブジェクトストレージ–データ容量がティアアウトチャージとして確保されるため、追加料金が発生します。


アドオン階層化サブスクリプションに含まれる料金は1回限りではありません。Keystoneのオンプレミスのファイルサービスとブロックサービス、およびサードパーティがサポートするオブジェクトストレージターゲット間の階層化関係を維持するには、期間全体で料金を支払う必要があります。

このソリューションで提供されるのは、コールドデータを低コストのターゲットストレージに階層化する機能のみで、パブリッククラウドやハイパースケーラーのインフラコストは発生しません。


NOTE: ハイパースケーラベースのコンピューティングおよびストレージインフラは、Keystoneサブスクリプションの一部としてネットアップから提供されるものではありません。ハイパースケーラークラウドサービスプロバイダから調達する必要があります。
