---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: アドオン、追加サービスの詳細、データ階層化 
---
= データの階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone （Keystone）サービスには、サブスクライブするファイルサービスとブロックサービスによる階層化機能があります。この機能を使用すると、使用頻度が低いデータを特定し、ネットアップが所有、導入、管理するコールドストレージに階層化できます。

このアドオンサービスには、Keystoneサブスクリプションの一部としてサブスクライブすることができます。ベースストレージとクラウドストレージサービスについては、を参照してください link:../concepts/supported-storage-services.html["サポートされているストレージサービス"]

サービスレベルの詳細については、を参照してください link:../concepts/service-levels.html["Keystoneのサービスレベル"]


NOTE: ネットアップストレージターゲットへのデータ階層化は、デフォルトでファイルストレージとブロックストレージのサービス階層に含まれています。このアドオンサービスが必要となるのは、データがAWS S3、Azure Blob、EMC ECSなどのネットアップ以外のストレージを階層化した場合のみです。

この階層化機能では、 NetApp FabricPool テクノロジを活用して、オンプレミスまたはオフプレミスの低コストのオブジェクトストレージ階層へデータを自動で階層化できます。この機能を使用すると、合意したサービスに基づいて、アクセス頻度の低いデータがオンプレミスまたはクラウドの低コストのストレージに自動的に階層化されます。

階層化サービスを使用すると、Extreme、Premium、Performance、Standard、Valueの各階層からオブジェクトターゲットへの階層化が可能になります。ホットティアとコールドティアはメーター制で、個別に請求されます。データの階層化は、価格を変更することなくいつでも追加でき、ホット/コールド比率の点で柔軟性が向上します。

この点について理解を深めるために、次の計算を実行してください。

コールドストレージ階層のターゲットが次の場合：

* 値階層（最大500TiB）、オブジェクト階層（500TiB以上）、既存のSGWSグリッド（お客様が所有）–追加料金は発生せず、基本的なストレージサービスの一部です。
* パブリッククラウド（AWS、Azure、Google）およびその他のサードパーティがサポートするオブジェクトストレージ–データ容量がティアアウトチャージとして確保されるため、追加料金が発生します。


アドオン階層化サブスクリプションに含まれる料金は1回限りの料金ではありません。Keystoneオンプレミスのファイルサービスとブロックサービス、およびサードパーティがサポートするオブジェクトストレージターゲット間の階層化関係を維持するために、期間全体で支払う必要があります。

このソリューションで提供されるのは、コールドデータを低コストのターゲットストレージに階層化する機能のみで、パブリッククラウドやハイパースケーラーのインフラコストは発生しません。


NOTE: ハイパースケーラベースのコンピューティングおよびストレージインフラは、Keystoneサブスクリプションの一部としてネットアップから提供されるものではなく、ハイパースケーラークラウドサービスプロバイダから調達する必要があります。
