---
sidebar: sidebar 
permalink: concepts/usps.html 
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support 
summary: United States Protected Supportは、米国内の米国市民から継続的なKeystoneサービスの提供とサポートを提供するアドオンサービスです。 
---
= USPSの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
米国保護サポート（USPS）は、NetApp Keystoneサブスクリプション向けのアドオンサービスです。パートナー様は、米国内の米国市民から継続的なKeystoneサービスの提供とサポートを受けることができます。

次のセクションを読み、このアドオンサービスに拘束され、NetApp Keystone 契約の条件に基づいて提供されているサブスクリプションの要素を確認してください。脚注：disclaimer1 [ここで説明するサービスとサービスは、完全に締結されたKeystone契約の対象となり、これらに限定され、これらに限定されます。]



== NetApp USPSの監視

NetApp USPS Keystoneサポートチームは、お客様の製品やサブスクリプションサービスの健常性を監視し、リモートサポートを提供し、Keystoneサクセスマネージャーと連携します。関連するKeystoneサブスクリプションの発注に関連付けられている製品を監視しているすべての担当者がUです。 米国で活動しているS市民。



== Keystone Success Managerの略

Keystone Success Manager（KSM）は米国米国で活動している市民土。担当業務は、NetApp Keystone 契約に明記されています。



== 展開アクティビティ

米国では、可能な場合、オンサイトおよびリモートでの導入および設置作業を行います米国の市民土。脚注：免責事項[オンサイトでの作業に適切な担当者が対応できるかどうかは、Keystoneシステムが導入されている地域によって異なります。]



== サポート

可能な場合は、必要なオンサイトのトラブルシューティングおよびサポート活動が米国によって実施されます米国の市民土。脚注:免責事項[]
