---
sidebar: sidebar 
permalink: installation/addl-req.html 
keywords: keystone unified manager prerequisites, aiqum config keystone 
summary: Keystone Unified Managerの前提条件 
---
= ONTAP およびStorageGRID のその他の前提条件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP とStorageGRID を使用する場合は、さらにいくつかの前提条件を満たす必要があります。Linux/VMware vSphereのシステム要件に加えて、これらの特定の前提条件を満たしていることを確認します。必要なタブをクリックして、詳細を確認してください。

[role="tabbed-block"]
====
.ONTAP
--
ONTAP にKeystone Collectorをインストールするには、前提条件として次の手順を実行します。

. Active IQ Unified Manager （Unified Manager）サーバがUnified Manager 9.7以降で設定されていることを確認します。Unified Managerのインストールについては、次のリンクを参照してください。
+
** https://["VMware vSphereシステムへのUnified Managerのインストール"^]
** https://["Linux システムへの Unified Manager のインストール"^]


. ONTAP クラスタがUnified Managerに追加されていることを確認します。クラスタの追加については、を参照してください https://["クラスタを追加する"^]。
. 使用状況やパフォーマンスのデータ収集用に特定のロールを持つUnified Managerユーザを作成します。次の手順を実行します。ユーザロールの詳細については、を参照してください https://["ユーザロールの定義"^]。
+
.. インストール時に生成されたデフォルトのアプリケーション管理者ユーザクレデンシャルを使用して、Unified Manager Web UIにログインします。を参照してください https://["Unified Manager Web UI にアクセスします"^]。
.. でKeystone Collectorのサービスアカウントを作成します `Operator` ユーザロール。Keystone CollectorサービスAPIは、このサービスアカウントを使用してUnified Managerと通信し、使用状況データを収集します。を参照してください https://["ユーザを追加する"^]。
.. を作成します `Database` を使用したユーザアカウント `Report Schema` ロール。このユーザは、パフォーマンスデータの収集に必要です。を参照してください https://["データベースユーザを作成しています"^]。


. Unified ManagerでAPIゲートウェイを有効にします。Keystone Collectorは、APIゲートウェイ機能を使用してONTAP クラスタと通信します。APIゲートウェイは、Web UIまたはUnified Manager CLIからいくつかのコマンドを実行して有効にすることができます。
+
.Web UI
Unified Manager Web UIからAPIゲートウェイを有効にするには、Unified Manager Web UIにログインしてAPIゲートウェイを有効にします。詳細については、を参照してください https://["API ゲートウェイを有効にしてい"^]。

+
.CLI の使用
Unified Manager CLIを使用してAPIゲートウェイを有効にするには、次の手順を実行します。

+
.. Unified Managerサーバで、SSHセッションを開始してUnified Manager CLIにログインします。
`um cli login -u _<umadmin>_`CLIコマンドの詳細については、を参照してください https://["Unified Manager の CLI コマンドがサポートされています"^]。
.. APIゲートウェイがすでに有効になっているかどうかを確認します。
`um option list api.gateway.enabled`A `true` この値は、APIゲートウェイが有効になっていることを示します。
.. の場合、返される値はです `false`次のコマンドを実行します。
`um option set api.gateway.enabled=true`
.. Unified Managerサーバを再起動します。
+
*** Linux ： https://["Unified Manager を再開しています"^]。
*** VMware vSphere： https://["Unified Manager 仮想マシンを再起動しています"^]。






--
.StorageGRID
--
StorageGRID にKeystone Collectorをインストールするには、次の設定が必要です。

* StorageGRID `11.4.0` 以降がインストールされている必要があります。StorageGRID のアップグレードについては、を参照してください link:https://docs.netapp.com/us-en/storagegrid-116/upgrade/index.html["StorageGRID ソフトウェアのアップグレード：概要"^]。
* 使用状況データを収集するために、StorageGRID ローカル管理者ユーザアカウントを作成する必要があります。このサービスアカウントは、Keystone Collectorサービスが管理ノードのAPIを介してStorageGRID と通信するために使用します。
+
.手順
.. Grid Managerにログインします。を参照してください https://["Grid Manager にサインインします"^]。
.. を使用してローカル管理者グループを作成します `Access mode: Read-only`。を参照してください https://["管理者グループを作成します"^]。
.. 次の権限を追加します。
+
*** テナントアカウント
*** メンテナンス
*** 指標クエリ


.. Keystoneサービスアカウントのユーザを作成し、adminグループに関連付けます。を参照してください https://["ユーザを管理します"]。




--
====