---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: ONTAPクラスタから送信される日 々 のサポートバンドルにKeystoneデータが組み込まれるようにAutoSupportを設定します。 
---
= Keystone向けのAutoSupportの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AutoSupportのテレメトリメカニズムを使用する場合、KeystoneはAutoSupportのテレメトリデータに基づいて使用量を計算します。必要なレベルのきめ細かさを実現するには、ONTAPクラスタから送信される日 々 のサポートバンドルにKeystoneデータが組み込まれるようにAutoSupportを設定する必要があります。

.このタスクについて
Keystoneデータを含めるようにAutoSupportを設定する前に、次の点に注意してください。

* AutoSupportテレメトリオプションを編集するには、ONTAP CLIを使用します。AutoSupportサービスおよびシステム（クラスタ）管理者ロールの管理については、を参照してください。 https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["Manage AutoSupport の概要"^] および https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["クラスタ管理者と SVM 管理者"^]。
* Keystoneの正確なデータ収集を保証するために、日単位と週単位のAutoSupportバンドルにサブシステムを含める必要があります。AutoSupportサブシステムの詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["AutoSupport サブシステムとは"^]。


.手順
. システム管理者ユーザとして、SSHを使用してKeystone ONTAPクラスタにログインします。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["SSHを使用したクラスタへのアクセス"^]。
. ログの内容を変更します。
+
** ONTAP 9.16.1 以降では、次のコマンドを実行して日次ログの内容を変更します。
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
+
クラスタがMetroCluster構成の場合、次のコマンドを実行します。

+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,object_store_server,san,raid,snapmirror,metrocluster -troubleshooting-additional wafl
----
** 以前のONTAPバージョンの場合は、次のコマンドを実行して日次ログの内容を変更します。
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,platform,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
+
クラスタがMetroCluster構成の場合、次のコマンドを実行します。

+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,platform,object_store_server,san,raid,snapmirror,metrocluster -troubleshooting-additional wafl
----
** 週次ログの内容を変更するには、次のコマンドを実行します。
+
[source]
----
autosupport trigger modify -autosupport-message weekly -troubleshooting-additional wafl -node *
----
+
このコマンドの詳細については、を参照してください https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["system node AutoSupport trigger modifyコマンドを実行します"^]。




