---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: Keystone Collectorをインストールする前に、必要なソフトウェアを使用してLinuxシステムを準備します。 
---
= Linuxシステムの要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
必要なソフトウェアを使用してLinuxシステムを準備することで、Keystone Collectorによる正確なインストールとデータ収集が保証されます。

LinuxおよびKeystone CollectorサーバVMがこれらの構成になっていることを確認します。

.Linuxサーバ：
* オペレーティングシステム：次のいずれか。
+
** Debian 12
** Red Hat Enterprise Linux 8.6以降の8.xバージョン
** Red Hat Enterprise Linux 9.0 以降のバージョン
** CentOS 7（既存環境のみ）


* クロニド時間同期
* 標準のLinuxソフトウェアリポジトリへのアクセス


同じサーバに次のサードパーティパッケージもインストールする必要があります。

* ポッドマン（ポッドマネージャー）
* SOS
* 時系列
* Python 3 (3.9.14 から 3.11.8)


.Keystone CollectorサーバのVM：
* コア：CPU×2
* RAM：4GBのRAM
* ディスク容量：50GBのvDisk




== その他の要件

次の一般的な要件が満たされていることを確認します。



=== ネットワーク要件

Keystone Collectorのネットワーク要件を次の表に示します。


NOTE: Keystoneコレクタにはインターネット接続が必要です。インターネット接続は、デフォルトゲートウェイ（NAT経由）またはHTTPプロキシ経由で直接ルーティングできます。ここでは、両方のバリエーションについて説明します。

|===


| ソース | 宛先 | サービス | プロトコルとポート | カテゴリ | 目的 


 a| 
Keystone Collector（Keystone ONTAP 向け）
 a| 
Active IQ Unified Manager （Unified Manager）
 a| 
HTTPS
 a| 
TCP 443
 a| 
必須（Keystone ONTAP を使用する場合）
 a| 
ONTAP のKeystone Collectorの使用状況指標の収集



 a| 
Keystone Collector（Keystone StorageGRID 向け）
 a| 
StorageGRID 管理ノード
 a| 
HTTPS
 a| 
TCP 443
 a| 
必須（Keystone StorageGRID を使用する場合）
 a| 
StorageGRID のKeystone Collectorの使用状況指標の収集



 a| 
Keystone Collector（汎用）
 a| 
インターネット（後で指定するURL要件に従って）
 a| 
HTTPS
 a| 
TCP 443
 a| 
必須（インターネット接続）
 a| 
Keystoneコレクタソフトウェア、OSの更新、指標のアップロード



 a| 
Keystone Collector（汎用）
 a| 
顧客のHTTPプロキシ
 a| 
HTTPプロキシ
 a| 
顧客プロキシポート
 a| 
必須（インターネット接続）
 a| 
Keystoneコレクタソフトウェア、OSの更新、指標のアップロード



 a| 
Keystone Collector（汎用）
 a| 
顧客のDNSサーバ
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
必須
 a| 
DNS解決



 a| 
Keystone Collector（汎用）
 a| 
顧客のNTPサーバ
 a| 
NTP
 a| 
UDP 123
 a| 
必須
 a| 
時刻の同期



 a| 
Keystone Collector（Keystone ONTAP 向け）
 a| 
Unified Manager の略
 a| 
MySQL
 a| 
TCP 3306
 a| 
オプションの機能
 a| 
Keystoneコレクタのパフォーマンス指標の収集



 a| 
Keystone Collector（汎用）
 a| 
カスタマーモニタリングシステム
 a| 
HTTPS
 a| 
TCP 7777
 a| 
オプションの機能
 a| 
Keystoneコレクタの健常性レポート



 a| 
顧客のOperationsワークステーション
 a| 
Keystoneコレクタ
 a| 
SSH
 a| 
TCP 22
 a| 
管理
 a| 
Keystoneコレクタ管理にアクセスする



 a| 
NetApp ONTAP クラスタおよびノード管理アドレス
 a| 
Keystoneコレクタ
 a| 
HTTP_8000、ping
 a| 
TCP 8000、ICMPエコー要求/応答
 a| 
オプションの機能
 a| 
ONTAP ファームウェアの更新用Webサーバ

|===

NOTE: MySQLのデフォルトポート3306は、Unified Managerの新規インストール時にlocalhostに制限されるため、Keystone Collectorのパフォーマンス指標が収集されません。詳細については、を参照してください link:addl-req.html["ONTAPの要件"]。



=== URLアクセス

Keystoneコレクタには、次のインターネットホストへのアクセスが必要です。

|===


| 住所 | 理由 


 a| 
https://keystone.netapp.com[]
 a| 
Keystoneコレクタソフトウェアの更新と使用状況のレポート



 a| 
https://support.netapp.com[]
 a| 
ネットアップHQによる請求情報とAutoSupport の提供

|===