---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: YUMソフトウェアリポジトリからKeystone Collectorソフトウェアをインストールします。 
---
= LinuxシステムへのKeystone Collectorのインストール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone Collectorソフトウェアは、RPMまたはDebianパッケージを使用してLinuxサーバにインストールできます。Linuxディストリビューションに応じて、インストール手順を実行します。

[role="tabbed-block"]
====
.RPMの使用
--
. KeystoneコレクタサーバにSSH接続し、に昇格します `root` 権限：
. Keystone公開署名をインポートします。
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. RPM データベースでKeystone Billing Platform のフィンガープリントをチェックして、正しい公開証明書がインポートされていることを確認します。
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` 正しい指紋は次のようになります。
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. ダウンロード `keystonerepo.rpm` ファイル：
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. ファイルの信頼性を確認します。
`rpm --checksig -v keystonerepo.rpm` 本物のファイルの署名は次のようになります。
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. YUMソフトウェアリポジトリファイルをインストールします。
`# yum install keystonerepo.rpm`
. Keystone repoがインストールされたら、YUMパッケージマネージャを使用してKeystoneコレクタパッケージをインストールします。
+
`# yum install keystone-collector`

+
Red Hat Enterprise Linux 9 の場合は、次のコマンドを実行して keystone-collector パッケージをインストールします。 
`# yum install keystone-collector-rhel9`



--
.Debianを使う
--
. Keystone CollectorサーバにSSHで接続し、権限を昇格し `root`ます。
`sudo su`
. ファイルをダウンロードし `keystone-sw-repo.deb`ます。
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Keystoneソフトウェアリポジトリファイルをインストールします。
`# dpkg -i keystone-sw-repo.deb`
. パッケージリストを更新します。
`# apt-get update`
. Keystoneリポジトリをインストールしたら、keystone-collectorパッケージをインストールします。
`# apt-get install keystone-collector`


--
====

NOTE: インストールが完了したら、Keystone Collector管理のターミナルユーザインターフェイス（TUI）ユーティリティを使用して設定と監視のアクティビティを実行できます。Enterキーや矢印キーなど、さまざまなキーボードコントロールを使用してオプションを選択し、このTUI間を移動できます。を参照してください link:../installation/configuration.html["Keystoneコレクタを設定する"] および link:../installation/monitor-health.html["システムヘルスを監視する"] を参照してください。
