---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: NetApp Keystone STaaSサービスの以前のリリースで見つかった問題は、以降のリリースで修正されています。 
---
= Keystone STaaSで解決された問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaSサービスの以前のリリースで見つかった問題は、以降のリリースで修正されています。

[cols="3*"]
|===
| 事象の説明 | 修正後 | リリースで修正 


 a| 
*Assets* タブでは、StorageGRID のアセットは表示されません。
 a| 
固定（ Fixed ）
 a| 
2025年6月19日



 a| 
Advance Data-Protect サービス レベルの場合、[消費傾向] タブのグラフに、プライマリ サイトとミラー サイトの分割が表示されます。
 a| 
チャートにはプライマリ サイトとミラー サイトの分割が表示されなくなりました。
 a| 
2025年6月19日



 a| 
Debianパッケージを使用してインストールされている既存のKeystone Collectorが、Keystone Collector管理TUIを使用してHTTPプロキシを設定するかUnified Managerを有効にしようとすると、TUIが応答しなくなります。
 a| 
固定（ Fixed ）
 a| 
2025年5月19日



 a| 
共通の設定がないため、Keystone Collector for StorageGRIDを正しく設定できません。
 a| 
固定（ Fixed ）
 a| 
2025年5月12日



 a| 
Keystone Collectorは、9.11より前のバージョンを実行しているONTAPクラスタの使用状況データの収集に失敗します。
 a| 
固定（ Fixed ）
 a| 
2025年4月30日



 a| 
リンクされたサブスクリプションの消費量の値に誤った負の数値が表示されるため、コミット済みの使用量の合計が誤って高く表示されます。
 a| 
固定（ Fixed ）
 a| 
2025年4月14日



 a| 
一部のサブスクリプションのサービスレベルについて、*消費トレンド*タブで履歴データを表示できません。
 a| 
固定（ Fixed ）
 a| 
2025年4月14日



 a| 
Digital Advisorダッシュボードの*[Watchlist]*に[Keystone Subscriptions]*オプションと[Reports]*に[Subscription Number]*オプションがありません。
 a| 
固定（ Fixed ）
 a| 
2025年3月19日



 a| 
Digital Advisorダッシュボードで監視リストを作成または変更したあとに、一部のKeystoneサブスクリプションが*監視リスト*に表示されない。
 a| 
固定（ Fixed ）
 a| 
2025年3月19日



 a| 
有効期限が切れていて、同じ追跡IDで更新されたがサービスレベルが異なるサブスクリプションに関連付けられているサービスレベルについては、*消費トレンド*タブで履歴データを表示できません。
 a| 
固定（ Fixed ）
 a| 
2025年3月19日



 a| 
Keystoneサブスクリプション*ページの*サブスクリプション*タブで10～12を超えるサブスクリプションを選択した場合、サブスクリプションのレポートを生成できません。
 a| 
固定（ Fixed ）
 a| 
2025/01/08



 a| 
StorageGRIDサブスクリプションの場合、*[ボリュームとオブジェクト]*タブの*[ボリュームの概要]*サブタブのロードに失敗します。
 a| 
固定（ Fixed ）
 a| 
2024/11/21



 a| 
日付範囲を選択する*開始日*フィールドには、*消費トレンド*タブに移動すると、デフォルトで将来の日付が表示されます。
 a| 
固定（ Fixed ）
 a| 
2024/09/04



 a| 
AQoSポリシーの設定時にKeystone Collector管理TUIが応答しなくなる。
 a| 
固定（ Fixed ）
 a| 
2024/08/07



 a| 
使用状況グラフには、* Capacity Trends *タブの* Capacity Trend *オプションから、前月の開始日と終了日として現在の日に対応する日付が選択されている場合、指定した1日の期間を超えたデータが表示されます。
 a| 
使用状況グラフに、指定した1日の期間のデータが正しく表示されるようになりました。
 a| 
2024年6月27日



 a| 
MetroCluster構成が設定されていないサブスクリプションの場合、* CVO Primary *と* CVO Secondary *のサービスレベルについては、* Capacity Trend *タブで過去の累積バーストデータを確認できません。
 a| 
固定（ Fixed ）
 a| 
2024年6月21日



 a| 
AutoSupportサブスクリプションの*[ボリュームの詳細]*タブに表示されるオブジェクトストレージの消費量の値が正しく表示されません。
 a| 
オブジェクトストレージの[Consumed]の値が正しく表示されるようになりました。
 a| 
2024年6月21日



 a| 
MetroCluster構成が設定されているAutoSupportサブスクリプションの*[アセット]*タブでクラスタレベルの情報を表示できません。
 a| 
固定（ Fixed ）
 a| 
2024年6月21日



 a| 
CSVレポートでKeystoneデータが正しく配置されていない*[Capacity Trend]*タブから生成されたCSVレポートの*[Account Name]*列に、カンマで区切ったアカウント名が含まれている場合 `(,)`。
 a| 
KeystoneデータがCSVレポートで正しくアライメントされている。
 a| 
2024年5月29日



 a| 
使用量がコミット済み容量を下回っていても、* Capacity Trend *タブに蓄積されたバースト使用量を表示します。
 a| 
固定（ Fixed ）
 a| 
2024年5月29日



 a| 
[Capacity Trend]*タブの*[Current Burst]*インデックスアイコンのツールチップテキストが正しくありません。
 a| 
正しいツールチップテキストが表示されます。"_現在消費されているバースト容量。これは、選択した日付範囲ではなく、現在の請求期間に適用されることに注意してください。_"
 a| 
2024年3月28日



 a| 
AutoSupportサブスクリプションで、AQoSに準拠していないボリュームやMetroClusterパートナーに関する情報は、Keystoneデータが24時間存在しない場合は提供されません。
 a| 
固定（ Fixed ）
 a| 
2024年3月28日



 a| 
1つのサービスレベルでのみAQoS準拠を満たす2つのサービスレベルがボリュームに割り当てられている場合、*[ボリュームの概要]*タブと*[ボリュームの詳細]*タブに表示されるAQoS非準拠ボリュームの数が一致しないことがあります。
 a| 
固定（ Fixed ）
 a| 
2024年3月28日



 a| 
AutoSupportサブスクリプションの*[アセット]タブには情報がありません。
 a| 
固定（ Fixed ）
 a| 
2024年3月14日



 a| 
階層化とオブジェクトストレージの両方のレートプランが適用される環境でMetroClusterとFabricPoolの両方が有効になっていると、ミラーボリューム（コンスティチュエントボリュームとFabricPoolボリュームの両方）のサービスレベルが誤って導かれる可能性があります。
 a| 
正しいサービスレベルがミラーボリュームに適用されている。
 a| 
2024年2月29日



 a| 
単一のサービスレベルまたはレートプランを使用する一部のサブスクリプションでは、[Volumes]タブのレポートのCSV出力に[AQoS compliance]列が表示されませんでした。
 a| 
コンプライアンス列はレポートに表示されます。
 a| 
2024年2月29日



 a| 
一部のMetroCluster環境では、*[パフォーマンス]*タブのIOPS密度グラフで異常が検出されることがありました。これは、ボリュームがサービスレベルに正確にマッピングされていないことが原因です。
 a| 
グラフが正しく表示されます。
 a| 
2024年2月29日



 a| 
バースト消費レコードの使用状況インジケータがオレンジで表示されていました。
 a| 
インジケータが赤で表示されます。
 a| 
2023年12月13日



 a| 
[Capacity Trend]、[Current Usage]、[Performance]の各タブの日付範囲とデータがUTCタイムゾーンに変換されませんでした。
 a| 
すべてのタブのクエリとデータの日付範囲は、UTC時間（サーバタイムゾーン）で表示されます。UTCタイムゾーンは、タブの各日付フィールドに対しても表示されます。
 a| 
2023年12月13日



 a| 
タブとダウンロードしたCSVレポートの開始日と終了日が一致していません。
 a| 
修正しました。
 a| 
2023年12月13日

|===