---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Keystone STaaSのリリースごとに解決された問題 
---
= 解決済みの問題です
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone STaaSサービスの以前のリリースで見つかった問題は、以降のリリースで修正されています。これらは修正です。

[cols="3*"]
|===
| 事象の説明 | 修正後 | リリースで修正 


 a| 
[Capacity Trend]*タブの*[Current Burst]*インデックスアイコンのツールチップテキストが正しくありません。
 a| 
正しいツールチップテキストが表示されます。"_現在消費されているバースト容量。これは、選択した日付範囲ではなく、現在の請求期間に適用されることに注意してください。_"
 a| 
2024年3月28日



 a| 
AutoSupportサブスクリプションで、AQoSに準拠していないボリュームやMetroClusterパートナーに関する情報は、Keystoneデータが24時間存在しない場合は提供されません。
 a| 
固定（ Fixed ）
 a| 
2024年3月28日



 a| 
1つのサービスレベルでのみAQoS準拠を満たす2つのサービスレベルがボリュームに割り当てられている場合、*[ボリュームの概要]*タブと*[ボリュームの詳細]*タブに表示されるAQoS非準拠ボリュームの数が一致しないことがあります。
 a| 
固定（ Fixed ）
 a| 
2024年3月28日



 a| 
AutoSupportサブスクリプションの*[アセット]タブには情報がありません。
 a| 
固定（ Fixed ）
 a| 
2024年3月14日



 a| 
階層化とオブジェクトストレージの両方のレートプランが適用される環境でMetroClusterとFabricPoolの両方が有効になっていると、ミラーボリューム（コンスティチュエントボリュームとFabricPoolボリュームの両方）のサービスレベルが誤って導かれる可能性があります。
 a| 
正しいサービスレベルがミラーボリュームに適用されている。
 a| 
2024年2月29日



 a| 
単一のサービスレベルまたはレートプランを使用する一部のサブスクリプションでは、[Volumes]タブのレポートのCSV出力に[AQoS compliance]列が表示されませんでした。
 a| 
コンプライアンス列はレポートに表示されます。
 a| 
2024年2月29日



 a| 
一部のMetroCluster環境では、*[パフォーマンス]*タブのIOPS密度グラフで異常が検出されることがありました。これは、ボリュームがサービスレベルに正確にマッピングされていないことが原因です。
 a| 
グラフが正しく表示されます。
 a| 
2024年2月29日



 a| 
バースト消費レコードの使用状況インジケータがオレンジで表示されていました。
 a| 
インジケータが赤で表示されます。
 a| 
2023年12月13日



 a| 
[Capacity Trend]、[Current Usage]、[Performance]の各タブの日付範囲とデータがUTCタイムゾーンに変換されませんでした。
 a| 
すべてのタブのクエリとデータの日付範囲は、UTC時間（サーバタイムゾーン）で表示されます。UTCタイムゾーンは、タブの各日付フィールドに対しても表示されます。
 a| 
2023年12月13日



 a| 
タブとダウンロードしたCSVレポートの開始日と終了日が一致していません。
 a| 
修正しました。
 a| 
2023年12月13日

|===