---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Keystone STaaSの既知の問題 
---
= Keystone STaaSの既知の問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の問題には、Keystoneサブスクリプションサービスの効果的な利用を妨げる可能性のある問題が記載されています。

NetApp Keystone STaaSで報告されている既知の問題は次のとおりです。

[cols="3*"]
|===
| Known 問題の略 | 説明 | 回避策 


 a| 
[Capacity Trends]タブで1日選択できる拡張データ表示。
 a| 
[Capacity Trends]タブの[Capacity Trend]*オプションから前月の開始日と終了日の両方として今日に対応する日付を選択すると、使用状況グラフには選択した開始日から現在の日付までの期間のデータが表示されます。 指定した1日の期間のデータを表示する代わりに、
 a| 
なし



 a| 
サービスレベルには過去の蓄積バーストデータは使用できません。
 a| 
MetroCluster構成が設定されていないサブスクリプションについては、*[Capacity Trend]*タブ内の* CVO Primary *および* CVO Secondary *サービスレベルの過去の累積バースト使用量データは表示されません。
 a| 
なし



 a| 
AutoSupportサブスクリプションのオブジェクトストレージ消費量の値が正しく表示されません。
 a| 
AutoSupportのテレメトリを使用してKeystoneデータを収集すると、ファイル、ブロック、オブジェクトの各サービスを含むサブスクリプションについて、*[Volume Details]*タブに表示されるオブジェクトストレージの消費値が正しく表示されません。
 a| 
正しい情報については、*[Current Usage]*タブに記載されているオブジェクトストレージの消費値を参照してください。



 a| 
クラスタレベルの情報を*[アセット]*タブで表示できません。
 a| 
MetroCluster構成が設定されたAutoSupportサブスクリプションの場合、クラスタレベルの詳細は*[アセット]*タブで確認できません。
 a| 
なし

|===