---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaSの新機能と機能強化： 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、Keystone STaaSサービスのリリースごとに新機能と強化された機能を提供します。



== 2024年5月9日の新機能と拡張機能

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）の[Keystone Subscriptions]*画面では、次の機能が強化されています。



=== CSVレポートの新しい列

[Capacity Trend]*タブのCSVレポートに、* Subscription Number *列と* Account Name *列が追加され、詳細が改善されました。



=== Enhanced Usage Typeカラム

[サブスクリプション]タブ内の[使用タイプ]列が拡張され、論理的および物理的な使用状況が、ファイルとオブジェクトの両方のサービスレベルをカバーするサブスクリプションのカンマ区切り値として表示されます。



=== [Volume Details]タブからオブジェクトストレージの詳細にアクセス

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブに、オブジェクトストレージの詳細と、ファイルとオブジェクトの両方のサービスレベルを含むサブスクリプションのボリューム情報が表示されるようになりました。[ボリュームの詳細]*タブで*[オブジェクトストレージの詳細]*ボタンをクリックすると、詳細を確認できます。



== 2024年3月28日の新機能と機能強化

Active IQデジタルアドバイザの[Keystoneサブスクリプション]*画面に次の機能強化が加えられました。



=== [Volume Details]タブでのQoSポリシー準拠状況の表示の改善

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブで、サービス品質（QoS）ポリシーへの準拠がわかりやすく表示されるようになりました。以前は「* AQoS *」と呼ばれていた列の名前が「* Compliant *」に変更され、QoSポリシーが準拠しているかどうかが示されます。また、ポリシーが固定かアダプティブかを示す新しい列* QoSポリシータイプ*が追加されました。どちらも当てはまらない場合は、列に「_not available_」と表示されます。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Volume Summary（ボリュームサマリ）タブの新しい列と簡素化されたサブスクリプション表示

* [ボリュームとオブジェクト]タブの*[ボリュームの概要]*タブに、*[保護]*というタイトルの新しい列が追加されました。この列には、サブスクライブ済みのサービスレベルに関連付けられている保護されているボリュームの数が表示されます。保護されているボリュームの数をクリックすると*[ボリュームの詳細]*タブが表示され、保護されているボリュームのフィルタリングされたリストを確認できます。
* [Volume Summary]*タブが更新され、アドオンサービスを除く基本サブスクリプションのみが表示されるようになりました。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。




=== [Capacity Trend]タブの[Accrued burst]の詳細表示への変更

[Capacity Trend]*タブの容量使用率棒グラフにカーソルを合わせると表示されるツールチップには、その月の発生したバーストの詳細が表示されます。過去1カ月間の詳細は表示されません。



=== Keystoneサブスクリプションの履歴データを表示するためのアクセスの強化

Keystoneサブスクリプションが変更または更新された場合に履歴データを表示できるようになりました。サブスクリプションの開始日を前の日付に設定して、次の情報を表示できます。

* [Capacity Trend]*タブでの消費量と累積バースト使用量のデータ
* ONTAPボリュームのパフォーマンス指標（*[パフォーマンス]*タブ）、


これらはすべて、サブスクリプションの選択した日付に基づいてデータが表示されます。



== 2024年2月29日の新機能と機能拡張

このリリースでは、Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）ダッシュボードと* Keystoneサブスクリプション*画面にいくつかの機能拡張が行われました。



=== [Assets]タブの追加

[Keystone Subscriptions]*画面に*[Assets]*タブが表示されるようになりました。この新しいタブには、サブスクリプションに基づいてクラスタレベルの情報が表示されます。詳細については、を参照してください link:../integrations/assets-tab.html["[Assets]タブ"^]。



=== [ボリュームとオブジェクト]タブの改善

ONTAPシステムボリュームをわかりやすくするために、*[ボリュームの概要]*と*[ボリュームの詳細]*という2つの新しいタブボタンが*[ボリューム]*タブに追加されました。[Volume Summary]*タブには、AQoS準拠ステータスや容量情報など、サブスクライブ済みのサービスレベルに関連付けられているボリュームの総数が表示されます。[ボリュームの詳細]*タブには、すべてのボリュームとその詳細が表示されます。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Digital Advisorでの検索機能の強化

Digital Advisor *画面の検索パラメータに、Keystoneサブスクリプション番号とKeystoneサブスクリプション用に作成された監視リストが表示されるようになりました。サブスクリプション番号または監視リスト名の最初の3文字を入力できます。詳細については、を参照してください link:../integrations/keystone-aiq.html["Active IQデジタルアドバイザのKeystoneダッシュボードを見る"^]。



=== 消費データのタイムスタンプの表示

消費データのタイムスタンプ（UTC）は、* Keystone Subscriptions *ウィジェットの古いダッシュボードで確認できます。



== 2024年2月13日の新機能と機能拡張

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）の* Keystoneサブスクリプション*画面に次の機能強化が加えられました。



=== プライマリサブスクリプションにリンクされているサブスクリプションを表示する機能

一部のプライマリサブスクリプションは、リンクされたセカンダリサブスクリプションを持つことができます。その場合、プライマリサブスクリプション番号は引き続き*サブスクリプション番号*列に表示され、リンクされたサブスクリプション番号は*サブスクリプション*タブの新しい列*リンクされたサブスクリプション番号*に表示されます。[リンクされたサブスクリプション]列は、リンクされたサブスクリプションがある場合にのみ使用可能になり、それらについて通知する情報メッセージが表示されます。



== 2024年1月11日の新機能と拡張機能

このリリースの新機能について説明します。

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれます）の* Keystoneサブスクリプション*画面では、以下の機能強化が行われています。



=== Accrued Burstに対して請求されたデータが返されました

[Capacity Trend]*タブの* Accrued Burst *のラベルが* Invoiced Accrued Burst *に変更されました。このオプションを選択すると、課金対象のバーストデータの月単位のグラフを表示できます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["請求済みバースト容量の表示"^]。



=== 特定の料金プランの発生した消費の詳細

_zero_committed容量のレートプランがあるサブスクリプションの場合は、* Capacity Trend *タブで消費量の詳細を確認できます。[Invoiced Accrued Consumption]*オプションを選択すると、課金されたAccrued Consumptionデータの月単位のグラフを表示できます。



== 2023年12月15日の新機能と拡張機能

このリリースの新機能について説明します。



=== 監視リストでの検索機能

Active IQデジタルアドバイザ（デジタルアドバイザ）の監視リストのサポートが拡張され、Keystoneシステムも対象になりました。監視リストで検索して、複数のお客様のサブスクリプションの詳細を表示できるようになりました。Keystone STaaSでの監視リストの使用の詳細については、を参照してください。 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone監視リストを使用して検索"^]。



=== UTCタイムゾーンに変換された日付

Active IQデジタルアドバイザの[Keystoneサブスクリプション]*画面のタブに返されるデータは、UTC時間（サーバのタイムゾーン）で表示されます。クエリの日付を入力すると、自動的にUTC時間であると見なされます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html["Keystoneサブスクリプションのダッシュボードとレポート"^]。
