---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaSの新機能と機能強化： 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、Keystone STaaSサービスのリリースごとに新機能と強化された機能を提供します。



== 2024年2月29日の新機能と機能拡張

このリリースでは、Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）ダッシュボードと* Keystoneサブスクリプション*画面にいくつかの機能拡張が行われました。



=== [Assets]タブの追加

[Keystone Subscriptions]*画面に*[Assets]*タブが表示されるようになりました。この新しいタブには、サブスクリプションに基づいてクラスタレベルの情報が表示されます。詳細については、を参照してください link:../integrations/assets-tab.html["[Assets]タブ"^]。



=== [ボリュームとオブジェクト]タブの改善

ONTAPシステムボリュームをわかりやすくするために、*[ボリュームの概要]*と*[ボリュームの詳細]*という2つの新しいタブボタンが*[ボリューム]*タブに追加されました。[Volume Summary]*タブには、AQoS準拠ステータスや容量情報など、サブスクライブ済みのサービスレベルに関連付けられているボリュームの総数が表示されます。[ボリュームの詳細]*タブには、すべてのボリュームとその詳細が表示されます。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Digital Advisorでの検索機能の強化

Digital Advisor *画面の検索パラメータに、Keystoneサブスクリプション番号とKeystoneサブスクリプション用に作成された監視リストが表示されるようになりました。サブスクリプション番号または監視リスト名の最初の3文字を入力できます。詳細については、を参照してください link:../integrations/keystone-aiq.html["Active IQデジタルアドバイザのKeystoneダッシュボードを見る"^]。



=== 消費データのタイムスタンプの表示

消費データのタイムスタンプ（UTC）は、* Keystone Subscriptions *ウィジェットの古いダッシュボードで確認できます。



== 2024年2月13日の新機能と機能拡張

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）の* Keystoneサブスクリプション*画面に次の機能強化が加えられました。



=== プライマリサブスクリプションにリンクされているサブスクリプションを表示する機能

一部のプライマリサブスクリプションは、リンクされたセカンダリサブスクリプションを持つことができます。その場合、プライマリサブスクリプション番号は引き続き*サブスクリプション番号*列に表示され、リンクされたサブスクリプション番号は*サブスクリプション*タブの新しい列*リンクされたサブスクリプション番号*に表示されます。[リンクされたサブスクリプション]列は、リンクされたサブスクリプションがある場合にのみ使用可能になり、それらについて通知する情報メッセージが表示されます。



== 2024年1月11日の新機能と拡張機能

このリリースの新機能について説明します。

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれます）の* Keystoneサブスクリプション*画面では、以下の機能強化が行われています。



=== Accrued Burstに対して請求されたデータが返されました

[Capacity Trend]*タブの* Accrued Burst *のラベルが* Invoiced Accrued Burst *に変更されました。このオプションを選択すると、課金対象のバーストデータの月単位のグラフを表示できます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["請求済みバースト容量の表示"^]。



=== 特定の料金プランの発生した消費の詳細

_zero_committed容量のレートプランがあるサブスクリプションの場合は、* Capacity Trend *タブで消費量の詳細を確認できます。[Invoiced Accrued Consumption]*オプションを選択すると、課金されたAccrued Consumptionデータの月単位のグラフを表示できます。



== 2023年12月15日の新機能と拡張機能

このリリースの新機能について説明します。



=== 監視リストでの検索機能

Active IQデジタルアドバイザ（デジタルアドバイザ）の監視リストのサポートが拡張され、Keystoneシステムも対象になりました。監視リストで検索して、複数のお客様のサブスクリプションの詳細を表示できるようになりました。Keystone STaaSでの監視リストの使用の詳細については、を参照してください。 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone監視リストを使用して検索"^]。



=== UTCタイムゾーンに変換された日付

Active IQデジタルアドバイザの[Keystoneサブスクリプション]*画面のタブに返されるデータは、UTC時間（サーバのタイムゾーン）で表示されます。クエリの日付を入力すると、自動的にUTC時間であると見なされます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html["Keystoneサブスクリプションのダッシュボードとレポート"^]。
