---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaSの新機能と機能強化： 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、Keystone STaaSサービスのリリースごとに新機能と強化された機能を提供します。

Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれる）の[Keystoneサブスクリプション]画面で、次の機能強化が導入されました。



== 2024年6月27日



=== サブスクリプションの一貫した表示

[Keystoneサブスクリプション]*画面が更新され、選択したサブスクリプション番号がすべてのタブに表示されます。

* [Keystoneサブスクリプション]*画面内のいずれかのタブが更新されると、画面は自動的に*[サブスクリプション]*タブに移動し、すべてのタブが*[サブスクリプション]*ドロップダウンに表示される最初のサブスクリプションにリセットされます。
* 選択したサブスクリプションがパフォーマンス指標にサブスクライブされていない場合、* Performance *タブには、ナビゲーション時に* Subscription *ドロップダウンにリストされた最初のサブスクリプションが表示されます。




== 2024年5月29日



=== エンハンスドバーストインジケータ

使用状況グラフインデックスの* Burst *インジケータが強化され、バースト制限のパーセンテージ値が表示されるようになりました。この値は、サブスクリプションで合意されたバースト制限に応じて変化します。また、* Usage Status *列の* Burst Usage *インジケーターにカーソルを合わせると、* Subscriptions *タブでバースト制限値を表示することもできます。



=== サービスレベルの追加

サービスレベル* CVO Primary *と* CVO Secondary *は、コミット済み容量がゼロのレートプランのサブスクリプション、またはメトロクラスタで構成されたサブスクリプションのCloud Volumes ONTAPをサポートするために含まれます。

* これらのサービスレベルの容量使用状況グラフは、* Keystone Subscriptions *ウィジェットと* Capacity Trend *タブの古いダッシュボードで確認できます。また、* Current Usage *タブの詳細な使用状況情報も確認できます。
* [サブスクリプション]タブでは、これらのサービスレベルは次のように表示されます。 `CVO (v2)` [Usage Type]列で、これらのサービスレベルに応じて課金を識別できます。




=== ズームイン機能でマイクロバーストの詳細を把握

[Capacity Trend]*タブにズームイン機能が追加され、マイクロバーストと呼ばれる短期的な急増の詳細が使用状況グラフに表示されるようになりました。詳細については、を参照してください link:../integrations/capacity-trend-tab.html["[Capacity Trend]タブ"^]。



=== サブスクリプションの表示の強化

サブスクリプションのデフォルト表示が拡張され、トラッキングIDでソートされるようになりました。*Subscriptions*タブのサブスクリプション（*Subscriptions*ドロップダウンおよびCSVレポートを含む）は、追跡IDのアルファベット順（a、a、b、Bなど）に基づいて表示されるようになりました。



=== 強化された累積バースト表示

[Capacity Trend]*タブの使用容量の棒グラフにカーソルを合わせると表示されるツールチップに、コミット済み容量に基づく累積バーストのタイプが表示されるようになりました。コミット済み容量レートプランがないサブスクリプションの場合は、暫定的な蓄積バーストと請求書による蓄積バーストを区別し、コミット済み容量がゼロの場合は*暫定的な蓄積消費*と*請求書による蓄積消費*、コミット済み容量がゼロでない場合は*暫定的な蓄積バースト*と*請求書による蓄積バースト*を表示します。



== 2024年5月9日



=== CSVレポートの新しい列

[Capacity Trend]*タブのCSVレポートに、* Subscription Number *列と* Account Name *列が追加され、詳細が改善されました。



=== Enhanced Usage Typeカラム

[サブスクリプション]タブ内の[使用タイプ]列が拡張され、論理的および物理的な使用状況が、ファイルとオブジェクトの両方のサービスレベルをカバーするサブスクリプションのカンマ区切り値として表示されます。



=== [Volume Details]タブからオブジェクトストレージの詳細にアクセス

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブに、オブジェクトストレージの詳細と、ファイルとオブジェクトの両方のサービスレベルを含むサブスクリプションのボリューム情報が表示されるようになりました。[ボリュームの詳細]*タブで*[オブジェクトストレージの詳細]*ボタンをクリックすると、詳細を確認できます。



== 2024年3月28日



=== [Volume Details]タブでのQoSポリシー準拠状況の表示の改善

[ボリュームとオブジェクト]タブの*[ボリュームの詳細]*タブで、サービス品質（QoS）ポリシーへの準拠がわかりやすく表示されるようになりました。以前は「* AQoS *」と呼ばれていた列の名前が「* Compliant *」に変更され、QoSポリシーが準拠しているかどうかが示されます。また、ポリシーが固定かアダプティブかを示す新しい列* QoSポリシータイプ*が追加されました。どちらも当てはまらない場合は、列に「_not available_」と表示されます。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Volume Summary（ボリュームサマリ）タブの新しい列と簡素化されたサブスクリプション表示

* [ボリュームとオブジェクト]タブの*[ボリュームの概要]*タブに、*[保護]*というタイトルの新しい列が追加されました。この列には、サブスクライブ済みのサービスレベルに関連付けられている保護されているボリュームの数が表示されます。保護されているボリュームの数をクリックすると*[ボリュームの詳細]*タブが表示され、保護されているボリュームのフィルタリングされたリストを確認できます。
* [Volume Summary]*タブが更新され、アドオンサービスを除く基本サブスクリプションのみが表示されるようになりました。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。




=== [Capacity Trend]タブの[Accrued burst]の詳細表示への変更

[Capacity Trend]*タブの容量使用率棒グラフにカーソルを合わせると表示されるツールチップには、その月の発生したバーストの詳細が表示されます。過去1カ月間の詳細は表示されません。



=== Keystoneサブスクリプションの履歴データを表示するためのアクセスの強化

Keystoneサブスクリプションが変更または更新された場合に履歴データを表示できるようになりました。サブスクリプションの開始日を前の日付に設定して、次の情報を表示できます。

* [Capacity Trend]*タブでの消費量と累積バースト使用量のデータ
* ONTAPボリュームのパフォーマンス指標（*[パフォーマンス]*タブ）、


これらはすべて、サブスクリプションの選択した日付に基づいてデータが表示されます。



== 2024年2月29日



=== [Assets]タブの追加

[Keystone Subscriptions]*画面に*[Assets]*タブが表示されるようになりました。この新しいタブには、サブスクリプションに基づいてクラスタレベルの情報が表示されます。詳細については、を参照してください link:../integrations/assets-tab.html["[Assets]タブ"^]。



=== [ボリュームとオブジェクト]タブの改善

ONTAPシステムボリュームをわかりやすくするために、*[ボリュームの概要]*と*[ボリュームの詳細]*という2つの新しいタブボタンが*[ボリューム]*タブに追加されました。[Volume Summary]*タブには、AQoS準拠ステータスや容量情報など、サブスクライブ済みのサービスレベルに関連付けられているボリュームの総数が表示されます。[ボリュームの詳細]*タブには、すべてのボリュームとその詳細が表示されます。詳細については、を参照してください link:../integrations/volumes-objects-tab.html["[ボリュームとオブジェクト]タブ"^]。



=== Digital Advisorでの検索機能の強化

Digital Advisor *画面の検索パラメータに、Keystoneサブスクリプション番号とKeystoneサブスクリプション用に作成された監視リストが表示されるようになりました。サブスクリプション番号または監視リスト名の最初の3文字を入力できます。詳細については、を参照してください link:../integrations/keystone-aiq.html["Active IQデジタルアドバイザのKeystoneダッシュボードを見る"^]。



=== 消費データのタイムスタンプの表示

消費データのタイムスタンプ（UTC）は、* Keystone Subscriptions *ウィジェットの古いダッシュボードで確認できます。



== 2024年2月13日



=== プライマリサブスクリプションにリンクされているサブスクリプションを表示する機能

一部のプライマリサブスクリプションは、リンクされたセカンダリサブスクリプションを持つことができます。その場合、プライマリサブスクリプション番号は引き続き*サブスクリプション番号*列に表示され、リンクされたサブスクリプション番号は*サブスクリプション*タブの新しい列*リンクされたサブスクリプション番号*に表示されます。[リンクされたサブスクリプション]列は、リンクされたサブスクリプションがある場合にのみ使用可能になり、それらについて通知する情報メッセージが表示されます。



== 2024年1月11日



=== Accrued Burstに対して請求されたデータが返されました

[Capacity Trend]*タブの* Accrued Burst *のラベルが* Invoiced Accrued Burst *に変更されました。このオプションを選択すると、課金対象のバーストデータの月単位のグラフを表示できます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["請求済みバースト容量の表示"^]。



=== 特定の料金プランの発生した消費の詳細

_zero_committed容量のレートプランがあるサブスクリプションの場合は、* Capacity Trend *タブで消費量の詳細を確認できます。[Invoiced Accrued Consumption]*オプションを選択すると、課金されたAccrued Consumptionデータの月単位のグラフを表示できます。



== 2023年12月15日



=== 監視リストでの検索機能

Digital Advisorで監視リストのサポートが拡張され、Keystoneシステムも対象になりました。監視リストで検索して、複数のお客様のサブスクリプションの詳細を表示できるようになりました。Keystone STaaSでの監視リストの使用の詳細については、を参照してください。 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone監視リストを使用して検索"^]。



=== UTCタイムゾーンに変換された日付

Digital Advisorの[Keystone Subscriptions]*画面のタブに返されるデータは、UTC時間（サーバのタイムゾーン）で表示されます。クエリの日付を入力すると、自動的にUTC時間であると見なされます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html["Keystoneサブスクリプションのダッシュボードとレポート"^]。
