---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaSの新機能と機能強化： 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、Keystone STaaSサービスのリリースごとに新機能と強化された機能を提供します。



== 2024年1月11日の新機能と拡張機能

このリリースの新機能について説明します。

Active IQデジタルアドバイザ（デジタルアドバイザ）の[Keystoneサブスクリプション]*画面に次の変更が加えられました。



=== Accrued Burstに対して請求されたデータが返されました

[Capacity Trend]*タブの* Accrued Burst *のラベルが* Invoiced Accrued Burst *に変更されました。このオプションを選択すると、課金対象のバーストデータの月単位のグラフを表示できます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["請求済みバースト容量の表示"^]。



=== 特定の料金プランの発生した消費の詳細

_zero_committed容量のレートプランがあるサブスクリプションの場合は、* Capacity Trend *タブで消費量の詳細を確認できます。[Invoiced Accrued Consumption]*オプションを選択すると、課金されたAccrued Consumptionデータの月単位のグラフを表示できます。



== 2023年12月15日の新機能と拡張機能

このリリースの新機能について説明します。



=== 監視リストでの検索機能

Active IQデジタルアドバイザ（デジタルアドバイザ）の監視リストのサポートが拡張され、Keystoneシステムも対象になりました。監視リストで検索して、複数のお客様のサブスクリプションの詳細を表示できるようになりました。Keystone STaaSでの監視リストの使用の詳細については、を参照してください。 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone監視リストを使用して検索"^]。



=== UTCタイムゾーンに変換された日付

Active IQデジタルアドバイザの[Keystoneサブスクリプション]*画面のタブに返されるデータは、UTC時間（サーバのタイムゾーン）で表示されます。クエリの日付を入力すると、自動的にUTC時間であると見なされます。詳細については、を参照してください link:../integrations/aiq-keystone-details.html["Keystoneサブスクリプションのダッシュボードとレポート"^]。
